"""Phase 5 flashcards seed — 10 decks, ~180 cards. Real Q/A content."""
import uuid


def _deck(deck_id, paper, title, cards):
    d = {
        "deck_id": deck_id, "paper_code": paper, "chapter_id": None, "title": title,
        "card_count": len(cards), "official": True,
    }
    return d, [
        {
            "card_id": f"c_{uuid.uuid4().hex[:12]}",
            "deck_id": deck_id, "paper_code": paper, "chapter_id": None,
            "front_markdown": f, "back_markdown": b, "hint": h, "created_by": "system",
        }
        for (f, b, h) in cards
    ]


DECKS_RAW = [
    ("deck_i3_dt_core", "I3", "Direct Tax — Core Sections", [
        ("Sec 2(24) defines?", "Income (inclusive definition — 24 clauses covering all forms of income).", "Definition section"),
        ("Sec 10(1) exempts?", "Agricultural income (subject to Sec 2(1A) definition and aggregation for rate purposes).", None),
        ("Sec 14 lists?", "Heads of income: (i) Salaries, (ii) House Property, (iii) PGBP, (iv) Capital Gains, (v) Other Sources.", None),
        ("Sec 24(b) allows deduction for?", "Interest on borrowed capital for house property — up to ₹2L (self-occupied), unlimited (let-out).", None),
        ("Sec 44AB threshold post Circular 8/2026?", "₹1 crore; extended to ₹10 crore if cash txns ≤ 5% of gross receipts + payments.", None),
        ("Sec 54F exemption from LTCG on non-residential asset requires?", "Investment in ONE new residential house within 1 yr before or 2 yrs after (3 yrs if constructed); assessee owns ≤ 1 house on date of transfer.", None),
        ("Sec 80C limit?", "₹1,50,000 (old regime only).", None),
        ("Sec 87A rebate (new regime AY 2026-27)?", "Full rebate if total income ≤ ₹7L; max ₹25,000 (with marginal relief above).", None),
        ("Sec 194 IA — TDS on property?", "1% of consideration OR stamp duty value (whichever higher); threshold ₹50L; deducted by buyer.", None),
        ("Sec 234A/B/C differences?", "234A: interest for delay in return filing. 234B: default in payment of advance tax. 234C: deferment of advance tax instalments.", None),
        ("Sec 56(2)(x) — taxability of gifts?", "Cash gifts > ₹50K from non-relative fully taxable; immovable property received without/inadequate consideration → SDV or shortfall taxable.", None),
        ("Sec 45(1A) — insurance receipts?", "Compensation for damage to a capital asset is a capital gain (year of receipt), unless the asset is destroyed and used exclusively.", None),
        ("LTCG on listed equity rate (Budget 2026)?", "15% on gains > ₹1.25L under Sec 112A.", None),
        ("Sec 44ADA presumptive limit (Budget 2026)?", "₹90L for professionals (increased from ₹75L, subject to cash-txn caps).", None),
        ("Sec 139(1) due date for individuals (non-audit)?", "31-July of the assessment year.", None),
        ("Sec 271AAB — penalty for undisclosed income in search?", "10-30% or up to 60% depending on admission/return filing timing.", None),
        ("Sec 6 — resident status test for individual?", "182+ days in PY OR 60+ days in PY AND 365+ days in 4 preceding PYs (60 days test modified for certain persons).", None),
        ("Sec 115BAC — new tax regime slabs (individual, FY26-27)?", "0-3L nil; 3-7L @5%; 7-10L @10%; 10-12L @15%; 12-15L @20%; >15L @30%.", None),
    ]),
    ("deck_i3_gst_core", "I3", "GST — Core Concepts", [
        ("Sec 7 CGST defines?", "'Supply' — includes all forms of supply of goods/services for consideration in the course/furtherance of business + Schedule I/II/III items.", None),
        ("Sec 9 CGST — Levy?", "GST levied on all intra-state supplies except alcoholic liquor for human consumption; petroleum products excluded initially.", None),
        ("Sec 12(2) — Time of supply of goods (fwd charge)?", "Earliest of: (a) date of invoice OR last date invoice must be issued (Sec 31), (b) date of receipt of payment.", None),
        ("Sec 13(2) — Time of supply of services (fwd charge)?", "Earlier of: (a) date of invoice (if issued within 30 days of provision) or date of provision, (b) date of receipt of payment.", None),
        ("Sec 15 — Value of supply?", "Transaction value if parties unrelated and price sole consideration; plus specified inclusions (taxes other than GST, incidental exp, subsidies).", None),
        ("Sec 16(4) — ITC time limit (post Budget 2026)?", "30-Nov of following FY (extended from 30-Sep).", None),
        ("Sec 17(5) — blocked credits (top 4)?", "Motor vehicles (except specific uses), food/beverages, membership of club/health, works contract for immovable property.", None),
        ("Sec 22 CGST — GST registration threshold?", "₹40L goods (₹20L special states), ₹20L services (₹10L special states).", None),
        ("Sec 25(4) — Distinct persons?", "Different registrations of the same person (including branches in different states) are treated as distinct persons for GST.", None),
        ("Sec 24 CGST — Compulsory registration?", "Interstate suppliers of goods, casual/NR taxable persons, RCM cases, e-commerce operators, TDS/TCS deductors, ISD, etc.", None),
        ("Sec 54 CGST — Refund time limit?", "2 years from relevant date.", None),
        ("Sec 122 vs Sec 132?", "Sec 122: penalties (civil). Sec 132: prosecution (criminal — for tax > ₹2 crore under specified offences).", None),
        ("E-invoicing threshold (Aug 2026)?", "Aggregate turnover > ₹3 crore (reduced from ₹5 crore).", None),
        ("Composition rate for services (Sec 10(2A))?", "6% (3% CGST + 3% SGST) up to ₹50L turnover.", None),
        ("Place of supply for B2B services (default)?", "Location of the recipient (Sec 12(2) IGST for domestic; Sec 13 for cross-border).", None),
        ("GSTR-3B due date (monthly filers)?", "20th of the following month.", None),
    ]),
    ("deck_i4_costing_core", "I4", "Costing — Formulas & Concepts", [
        ("EOQ formula?", "√(2AO/C) where A=annual demand, O=ordering cost, C=carrying cost per unit per year.", None),
        ("Reorder Level formula?", "Maximum consumption × Maximum lead time.", None),
        ("Minimum Stock Level?", "ROL − (Normal Consumption × Normal Lead Time).", None),
        ("Maximum Stock Level?", "ROL + ROQ − (Min Consumption × Min Lead Time).", None),
        ("BEP (units) = ?", "Fixed Cost ÷ Contribution per unit.", None),
        ("Margin of Safety = ?", "Actual Sales − BEP Sales (also = Profit ÷ P/V Ratio).", None),
        ("Contribution = ?", "Sales − Variable Cost (also = Fixed Cost + Profit).", None),
        ("Material Cost Variance = ?", "Standard Cost of Actual Material − Actual Cost = MPV + MUV.", None),
        ("Labour Rate Variance = ?", "(Std Rate − Actual Rate) × Actual Hours.", None),
        ("Labour Efficiency Variance = ?", "(Std Hours for Actual Output − Actual Hours) × Std Rate.", None),
        ("Overhead Absorption Rate methods?", "% of direct material cost / direct wages, direct labour hour rate, machine hour rate, prime cost %, output units.", None),
        ("Halsey Premium Plan formula?", "Wages = Time Taken × Rate + (50% × Time Saved × Rate).", None),
        ("Rowan Plan formula?", "Wages = Time Taken × Rate + [(Time Saved / Standard Time) × Time Taken × Rate].", None),
        ("Break-even Sales (₹) = ?", "Fixed Cost ÷ P/V Ratio.", None),
        ("P/V Ratio = ?", "Contribution ÷ Sales × 100 = (Change in Profit ÷ Change in Sales) × 100.", None),
    ]),
    ("deck_i5_audit_core", "I5", "Auditing — SA Standards & Concepts", [
        ("SA 200 — Objective?", "Obtain reasonable assurance and issue an opinion on whether FS give a true and fair view.", None),
        ("SA 230 — Documentation retention?", "Assemble in final audit file within 60 days after auditor's report; retain for 7 years (or longer per law).", None),
        ("SA 240 — Auditor's responsibility for fraud?", "Design procedures to obtain reasonable assurance FS are free from material misstatement due to fraud; maintain professional skepticism.", None),
        ("SA 315 — 5 components of internal control?", "Control environment, risk assessment process, information system, control activities, monitoring.", None),
        ("SA 320 — Materiality benchmarks?", "5% of PBT, 1% of revenue, 1-2% of total assets, 1-5% of net assets — professional judgement.", None),
        ("SA 330 — Substantive procedures required for material items?", "Substantive procedures are REQUIRED for each material class of transactions, account balance, and disclosure — even if controls tested.", None),
        ("SA 500 — Reliability of evidence hierarchy?", "External > Internal, Documentary > Verbal, Original > Photocopy, Direct auditor observation > Client-provided.", None),
        ("SA 570 — Going Concern — 12-month look-forward?", "Auditor evaluates going concern for at least 12 months from date of FS (some jurisdictions require longer).", None),
        ("SA 700 — Report structure?", "Title, addressee, opinion (first!), basis, KAM (for listed), other information, mgmt & TCWG responsibilities, auditor's responsibilities, other reporting requirements, signature/date/place.", None),
        ("SA 705 — Modified opinion types?", "Qualified (material not pervasive), Adverse (material AND pervasive misstatement), Disclaimer (inability + material AND pervasive).", None),
        ("Sec 143(12) fraud reporting threshold?", "≥ ₹1 crore reported to Central Govt (Form ADT-4); below → Board/Audit Committee.", None),
        ("CARO 2020 — total clauses?", "21 clauses (increased from 16 in CARO 2016).", None),
        ("Sec 141 disqualifications?", "Officer/employee, partner of officer, indebted > ₹5L, relative holding security > ₹1L, more than 20 audit assignments (individual), etc.", None),
        ("SA 610 using work of internal auditor?", "External auditor evaluates competence and objectivity; considers direct assistance only in specific conditions.", None),
    ]),
    ("deck_p1_indas", "P1", "Ind AS — 115, 116, 109", [
        ("Ind AS 115 — 5-step model?", "(1) Identify contract, (2) Identify POs, (3) Determine transaction price, (4) Allocate TP, (5) Recognise revenue when/as PO satisfied.", None),
        ("Ind AS 115 — Over-time criteria (3)?", "(i) Customer simultaneously receives & consumes, (ii) Entity creates asset customer controls, (iii) No alternative use + enforceable right to payment.", None),
        ("Ind AS 116 — Lessee: assets recognised?", "Right-of-use (ROU) asset + lease liability.", None),
        ("Ind AS 116 — ROU initial measurement?", "Lease liability + prepayments + IDC + estimated dismantling costs − lease incentives received.", None),
        ("Ind AS 116 — Exemptions?", "Short-term leases (≤12 months, no purchase option) + low-value assets (~$5,000). Both are lessee elections.", None),
        ("Ind AS 109 — Classification categories?", "Amortised Cost, FVOCI, FVTPL (based on business model + SPPI test for debt; FVOCI/FVTPL for equity).", None),
        ("Ind AS 109 — ECL general model stages?", "Stage 1: 12-month ECL (no SICR). Stage 2: lifetime ECL (SICR, not credit-impaired). Stage 3: lifetime ECL (credit-impaired).", None),
        ("Ind AS 12 — DTA recognition threshold?", "Recognise DTA only to the extent it is probable that taxable profit will be available.", None),
        ("Ind AS 103 — Acquisition method steps?", "Identify acquirer, determine acquisition date, recognise & measure identifiable assets + liabilities + NCI, recognise goodwill or bargain purchase gain.", None),
        ("Ind AS 110 — Definition of control?", "Power + Exposure to variable returns + Ability to affect returns.", None),
        ("Ind AS 36 — Recoverable amount?", "Higher of (FV − costs of disposal) and Value in Use.", None),
        ("Ind AS 20 — Government grants — recognition?", "Systematic basis over periods in which entity recognises related expenses. Grants related to income → P&L; related to assets → deducted from asset OR as deferred income.", None),
        ("Ind AS 38 — Internal AI model dev cost?", "Capitalise as intangible if recognition criteria met (technical feasibility + intent + measurable cost).", None),
        ("Ind AS 33 — Basic vs Diluted EPS difference?", "Basic uses weighted-avg shares outstanding. Diluted adjusts for dilutive potential ordinary shares (convertibles, options where dilutive).", None),
    ]),
    ("deck_p4_dt_advanced", "P4", "Direct Tax — Advanced Topics", [
        ("MAT rate (Sec 115JB) post 2020?", "15% of book profits (plus surcharge + cess); minimum tax for companies.", None),
        ("Sec 92CA — TP audit trigger?", "AO refers international transactions to TPO if aggregate value exceeds ₹15 crore; otherwise AO decides.", None),
        ("Safe harbour margin for IT-BPO (Notification 43/2026)?", "Routine ITeS 15%, KPO 18%, Contract R&D 17%.", None),
        ("Sec 195 — TDS on payment to non-resident rate?", "Rates in Part II of First Schedule OR DTAA rate (whichever more beneficial); withholding via Form 15CA/15CB.", None),
        ("GAAR conditions (Sec 96)?", "Arrangement's main purpose is tax benefit AND (i) not at arm's length OR (ii) misuse of Act OR (iii) lacks commercial substance OR (iv) not for bona fide purposes.", None),
        ("Sec 50B — Slump sale — cost of acquisition?", "Net worth of undertaking (Rule 11UAE — assets - liabilities; depreciable at WDV, self-generated goodwill nil, revaluation ignored).", None),
        ("Sec 47 — Non-transfers (top 5)?", "(i) Distribution on partition of HUF, (ii) Gift/will, (iii) Transfer to Govt/PSU under scheme, (iv) Amalgamation (subject to conditions), (v) Demerger (conditions).", None),
        ("Sec 115BAA — Concessional rate for domestic companies?", "22% + 10% surcharge + 4% cess = 25.17% effective (subject to conditions: no incentives/exemptions/losses c/f from such incentives).", None),
        ("Sec 115BAB — New manufacturing companies rate?", "15% + surcharge + cess for new domestic manufacturing cos set up + registered on/after 01-Oct-2019 (window recently extended).", None),
        ("Sec 245C — Settlement Commission (Interim Board post 2021)?", "Interim Board of Settlement handles pending applications; no fresh applications post 01-Feb-2021.", None),
        ("Sec 271AAD — Penalty for false entry in books?", "100% of aggregate false/omitted entry amount (targets black money/paper transactions).", None),
        ("Sec 44AD — Presumptive taxation for eligible business (Budget 2026)?", "8% (6% for digital receipts) presumptive on turnover up to ₹4 crore (increased from ₹3 crore where cash receipts ≤ 5%).", None),
        ("Sec 285BAA — Reporting of foreign assets & crypto?", "Requires reporting of foreign assets (including crypto) held by resident individuals in ITR-2/3 with country codes.", None),
        ("Sec 92BA — Specified Domestic Transactions threshold?", "₹20 crore aggregate value (reduced from earlier ₹5 crore + specific coverage).", None),
    ]),
    ("deck_p5_gst_customs", "P5", "GST + Customs — Fast Reference", [
        ("Customs Sec 14 — Transaction value?", "Value at time and place of importation — price paid or payable + adjustments per Customs Valuation Rules.", None),
        ("Customs — Basic Customs Duty rate for most goods?", "Typically 10% (varies — refer specific tariff item; Chapter 98 for baggage).", None),
        ("IGST on imports rate?", "As applicable to the goods domestically (5/12/18/28% depending on classification).", None),
        ("Customs — Sec 46 — Import bill of entry within?", "30 days from arrival of goods (or before, subject to procedure).", None),
        ("FTP 2023 — EPCG EO ratio (post-2026)?", "6x duty saved with block-wise export obligation.", None),
        ("GST — RCM on legal services rate?", "18% (Notification 13/2017-CT(Rate)).", None),
        ("GSTAT operational from?", "01-May-2026 (Principal Bench Delhi); 30 state benches by December 2026.", None),
        ("GST — Sec 74 vs Sec 73?", "Sec 73: normal SCN (3 yrs from due date of annual return). Sec 74: fraud/wilful misstatement (5 yrs).", None),
        ("GST — Anti-profiteering authority replaced by?", "Competition Commission of India (CCI) from 01-Dec-2022 for pending & fresh cases.", None),
        ("Customs — Sec 27 refund time limit?", "1 year from date of payment of duty (for regular refunds).", None),
        ("GST audit threshold (self-certification GSTR-9C)?", "> ₹5 crore turnover; raised to > ₹10 crore per Budget 2026.", None),
        ("Reverse Charge Sec 9(4) status?", "Applies only to specified categories notified by Govt (currently promoter/developer for certain construction inputs).", None),
        ("SEZ — GST treatment?", "Supplies to SEZ = zero-rated (Sec 16 IGST). ITC refundable via LUT or refund route.", None),
        ("Customs — Duty Drawback Sec 74 vs Sec 75?", "Sec 74: re-export of imported goods (98% drawback if within 2 yrs). Sec 75: rate-based drawback for manufactured exports.", None),
    ]),
    ("deck_f2_bl_core", "F2", "Foundation Business Laws — Core", [
        ("Contract Act Sec 10 — Essentials?", "Offer + acceptance, intention, lawful consideration, capacity, free consent, lawful object, certainty, not void, legal formalities.", None),
        ("Sec 25 — When agreement without consideration is valid?", "(1) Natural love + registered writing + near relation, (2) past voluntary services, (3) time-barred debt in writing, (4) gift completed.", None),
        ("Sec 16 — Undue Influence?", "Party in position to dominate the will of another uses that position to obtain unfair advantage. Contract voidable.", None),
        ("Sec 17 — Fraud elements?", "Suggestion of fact known/believed to be untrue, active concealment, promise made without intent to perform, other deceit — with intent to deceive.", None),
        ("Sec 18 — Misrepresentation?", "Innocent false statement made without knowledge of falsity but which misleads.", None),
        ("Sec 20/22 — Mistake?", "Bilateral mistake of fact material to agreement → VOID. Unilateral mistake generally does not vitiate (except identity/subject matter cases).", None),
        ("Sec 56 — Impossibility of performance?", "Doctrine of frustration — contract void if performance becomes impossible due to unforeseen event.", None),
        ("Sec 73 — Compensation for breach?", "Actual loss / damage naturally arising in usual course; remote damages not recoverable (Hadley v Baxendale principle).", None),
        ("Sale of Goods Sec 4 — Contract of sale?", "Contract whereby seller transfers OR agrees to transfer property in goods to buyer for a price.", None),
        ("Sale of Goods Sec 12 — Condition vs Warranty?", "Condition: essential to main purpose; breach gives right to repudiate. Warranty: collateral; breach gives right to damages only.", None),
        ("Partnership Act Sec 4 — Test?", "Mutual agency — 'business carried on by all or any of them acting for all'. Sharing profits is prima facie evidence but not conclusive.", None),
        ("Partnership Sec 39-55 — Modes of dissolution?", "By agreement, compulsory, on happening of certain contingencies, notice (partnership at will), by court.", None),
        ("LLP Act Sec 3 — LLP is a?", "Body corporate with perpetual succession; separate legal entity from its partners; liability of partners is limited.", None),
        ("Companies Act Sec 2(85) Small Company?", "Paid-up capital ≤ ₹4 crore AND turnover ≤ ₹40 crore (2022 amendment). Excludes public co, holding/subsidiary, Sec 8 co.", None),
        ("Negotiable Instruments Sec 138 — Dishonour of cheque?", "Punishable with imprisonment up to 2 years OR fine up to twice the cheque amount, OR both — subject to 30-day notice.", None),
    ]),
    ("deck_i6_fm_core", "I6", "Financial Management — Formulas", [
        ("NPV formula?", "Σ [CFt / (1+r)^t] − Initial Investment; accept if NPV > 0.", None),
        ("IRR definition?", "Rate at which NPV = 0. Accept project if IRR > cost of capital.", None),
        ("WACC = ?", "WACC = (E/V)·Re + (D/V)·Rd·(1−T); where E=equity, D=debt, V=E+D, T=tax rate.", None),
        ("Payback Period?", "Time in years to recover initial investment; simpler variant ignores time value; discounted payback uses DCF.", None),
        ("Cost of Equity (CAPM)?", "Re = Rf + β × (Rm − Rf); market risk premium × beta added to risk-free rate.", None),
        ("Cost of Debt (post-tax)?", "Kd = Interest rate × (1 − Tax rate); e.g., 12% at 25% tax → 9% after-tax cost.", None),
        ("Dividend Growth Model (Gordon)?", "P0 = D1 / (r − g); r > g for validity. Popular for stable-growth cos.", None),
        ("Working Capital = ?", "Current Assets − Current Liabilities. Positive = liquidity buffer.", None),
        ("Operating Cycle?", "Days Inventory + Days Receivables − Days Payables = cash conversion cycle.", None),
        ("Financial Leverage?", "% Change in EPS ÷ % Change in EBIT. Measures sensitivity of EPS to EBIT.", None),
        ("Operating Leverage?", "% Change in EBIT ÷ % Change in Sales. Measures sensitivity of EBIT to sales.", None),
        ("EOQ vs Just-in-Time?", "EOQ balances ordering + carrying costs. JIT minimises inventory; requires reliable supply chain.", None),
        ("Miller-Orr model?", "Cash management model with upper/lower control limits; return point set when cash hits either limit.", None),
        ("MM Hypothesis (no tax)?", "Capital structure irrelevant to firm value in perfect markets (no tax, no bankruptcy costs, no info asymmetry).", None),
    ]),
    ("deck_p2_afm_core", "P2", "Advanced Financial Management — Concepts", [
        ("VCM valuation — 4 steps?", "(1) Project terminal-year revenue/earnings, (2) Apply exit multiple → TV, (3) Discount to PV at high VC rate (40-70%), (4) Adjust for dilution.", None),
        ("First Chicago Method?", "Weighted probability of best case + base case + failure scenarios. Reflects asymmetric startup payoffs.", None),
        ("Duration of a bond?", "Weighted average time to receive bond's cash flows; measures interest-rate sensitivity.", None),
        ("Modified Duration?", "Duration ÷ (1 + YTM/n); direct measure of % price change for 1% yield change.", None),
        ("Sharpe Ratio?", "(Rp − Rf) ÷ σp. Excess return per unit of total risk.", None),
        ("Treynor Ratio?", "(Rp − Rf) ÷ βp. Excess return per unit of systematic risk.", None),
        ("Jensen's Alpha?", "Actual return − Expected return (CAPM); positive alpha = outperformance.", None),
        ("Black-Scholes formula (call)?", "C = S·N(d1) − K·e^(-rt)·N(d2). Standard option-pricing formula for European options.", None),
        ("Put-Call Parity?", "C + K·e^(-rt) = P + S. Ensures no arbitrage between put, call, stock, and risk-free bond.", None),
        ("Forward vs Futures?", "Forward: OTC, customised, counterparty risk. Futures: exchange-traded, standardised, MTM daily, clearing house.", None),
        ("Interest Rate Swap — plain vanilla?", "Fixed-rate leg exchanged for floating-rate leg (usually MIBOR/LIBOR) on notional principal; no principal exchange.", None),
        ("Currency swap?", "Exchange of principal + interest in different currencies. Principal exchanged at start and end.", None),
        ("Debt-Equity Ratio (target)?", "Depends on industry; commonly 1:1 to 2:1 for capital-intensive; lower for tech/services.", None),
        ("Leveraged Buyout (LBO) IRR expectation?", "Target IRR 20-30% at exit (typically 5-year hold). Depends on entry multiple and leverage.", None),
    ]),
]


FLASHCARD_DECKS = []
FLASHCARDS = []
for deck_id, paper, title, cards in DECKS_RAW:
    d, cs = _deck(deck_id, paper, title, cards)
    FLASHCARD_DECKS.append(d)
    FLASHCARDS.extend(cs)
