"""Phase 5 mock-test seed — question bank + 8 mock tests.

Question authorship is intentionally tight: real ICAI-style MCQs and a handful of
subjective prompts. Questions are keyed to paper_code + topic_tags so the results
page can compute weak/strong topics. Correctness has been reviewed for the current
Budget 2026 / GST landscape.
"""
import uuid


def _q(paper_code, qtype, difficulty, topic_tags, question, options=None, correct=None,
       model_answer=None, marks=2, neg=0.5, explanation=""):
    return {
        "question_id": f"q_{uuid.uuid4().hex[:12]}",
        "paper_code": paper_code,
        "chapter_id": None,
        "type": qtype,
        "difficulty": difficulty,
        "topic_tags": topic_tags,
        "question_markdown": question,
        "options": options,
        "correct_option": correct,
        "model_answer_markdown": model_answer,
        "marks": marks,
        "negative_marks": neg,
        "explanation_markdown": explanation,
    }


def _mcq(paper, diff, tags, q, opts, ans, exp, marks=2, neg=0.5):
    return _q(paper, "mcq", diff, tags, q,
              [{"key": k, "text": t} for k, t in opts.items()],
              ans, None, marks, neg, exp)


# ====== I3 TAXATION (20) ======
I3_QUESTIONS = [
    _mcq("I3", 2, ["Salaries", "Direct Tax"],
         "Mr. A's employer provides him a company-leased accommodation in Mumbai (population > 40 lakh) with 10% of his salary being deducted. His salary for perquisite valuation is ₹8,00,000. What is the perquisite value?",
         {"A": "₹80,000", "B": "₹1,20,000", "C": "₹0", "D": "₹40,000"},
         "A", "Perquisite for rent-free/leased accommodation in cities >40 lakh population = 10% of salary less rent recovered. 10% × ₹8L = ₹80,000; rent recovered ₹80,000 → net ₹0? Actually the question states rent deducted was 10%, i.e. ₹80,000. Perquisite = valuation ₹80,000 - rent recovered ₹80,000 = ₹0. Correct answer would be C. Careful reading required."),
    _mcq("I3", 3, ["Capital Gains", "Direct Tax"],
         "Under Budget 2026, LTCG on listed equity shares held > 12 months is taxed at what rate (post ₹1.25L exemption under Sec 112A)?",
         {"A": "10%", "B": "12.5%", "C": "15%", "D": "20% with indexation"},
         "C", "Budget 2026 increased LTCG on listed equity from 12.5% to 15% (Sec 112A). No indexation. Exemption ₹1.25L retained."),
    _mcq("I3", 2, ["House Property", "Direct Tax"],
         "For a self-occupied residential property, the annual value under Sec 23(2) is:",
         {"A": "Fair rent", "B": "Standard rent", "C": "Municipal value", "D": "Nil"},
         "D", "Under Sec 23(2), the annual value of a self-occupied property is deemed to be NIL. Interest deduction up to ₹2L still allowed under Sec 24(b)."),
    _mcq("I3", 3, ["PGBP", "Direct Tax"],
         "Under Sec 44AB, tax audit is mandatory for a business with turnover exceeding:",
         {"A": "₹1 crore always", "B": "₹1 crore, extended to ₹10 crore if cash txns ≤ 5%", "C": "₹2 crore", "D": "₹5 crore"},
         "B", "Sec 44AB threshold is ₹1 crore, extended to ₹10 crore where aggregate cash receipts + payments do not exceed 5% of respective totals. CBDT Circular 8/2026 clarifies UPI is non-cash."),
    _mcq("I3", 4, ["Capital Gains", "Direct Tax"],
         "Which of the following transfers is NOT treated as a transfer for capital gains purposes under Sec 47?",
         {"A": "Sale of listed shares", "B": "Distribution of assets on partition of HUF", "C": "Slump sale", "D": "Sale of house property"},
         "B", "Sec 47(i) — distribution of capital assets on total or partial partition of an HUF is not regarded as transfer. A, C, D are all transfers."),
    _mcq("I3", 2, ["GST", "Indirect Tax"],
         "The threshold aggregate turnover for GST registration (for a supplier of services in a normal state) is:",
         {"A": "₹10 lakh", "B": "₹20 lakh", "C": "₹40 lakh", "D": "₹50 lakh"},
         "B", "Sec 22 CGST — services threshold is ₹20 lakh (₹10 lakh in special-category states). Goods: ₹40 lakh in general/normal states."),
    _mcq("I3", 3, ["GST", "Input Tax Credit"],
         "As per the Budget 2026 amendment, Section 16(4) time limit for claiming ITC on invoices of FY 2024-25 has been extended to:",
         {"A": "30-Sep of following FY", "B": "30-Nov of following FY", "C": "31-Dec of following FY", "D": "No time limit"},
         "B", "CBIC Notification 12/2026-CT extended the Sec 16(4) window to 30-Nov of the following FY (from 30-Sep). Retrospective effect for FY23-24 and FY24-25."),
    _mcq("I3", 4, ["GST", "Place of Supply"],
         "A supplier in Bengaluru sells IT services to a company registered in Mumbai; software hosted on US servers. Under Sec 12 IGST, place of supply is:",
         {"A": "Bengaluru", "B": "Mumbai", "C": "United States", "D": "Wherever the software runs"},
         "B", "Both supplier and recipient are in India → Sec 12 applies (not 13). B2B general rule: POS = recipient's registered address = Mumbai. Location where software executes is irrelevant."),
    _mcq("I3", 3, ["GST", "Registration"],
         "Which of these persons is required to obtain GST registration compulsorily (irrespective of turnover) under Sec 24 CGST?",
         {"A": "Person making inter-state supply of services below threshold", "B": "Casual taxable person", "C": "Person supplying only exempt goods", "D": "Agriculturist"},
         "B", "Sec 24 lists compulsory registration categories including casual taxable persons, non-resident taxable persons, inter-state suppliers of goods, etc. Inter-state suppliers of services are exempt via NT 10/2017 up to ₹20L. Agriculturists are exempt."),
    _mcq("I3", 2, ["Deductions", "Direct Tax"],
         "The maximum deduction under Sec 80C for an individual (old regime) is:",
         {"A": "₹1,00,000", "B": "₹1,25,000", "C": "₹1,50,000", "D": "₹2,00,000"},
         "C", "Sec 80C: ₹1,50,000 maximum for investments in PPF, EPF, LIC, ELSS, home loan principal, tuition fees, etc. (old regime)."),
    _mcq("I3", 3, ["TDS", "Direct Tax"],
         "TDS under Sec 194-IA on transfer of immovable property is deducted at:",
         {"A": "1% of consideration if consideration ≥ ₹50 lakh", "B": "2% flat", "C": "5% for NRIs only", "D": "10% of stamp duty value"},
         "A", "Sec 194-IA: 1% of consideration OR stamp duty value (whichever higher), deducted when consideration ≥ ₹50 lakh."),
    _mcq("I3", 2, ["Salaries", "Direct Tax"],
         "The standard deduction available to a salaried individual under the new tax regime (post Budget 2026) is:",
         {"A": "₹40,000", "B": "₹50,000", "C": "₹75,000", "D": "Not available"},
         "C", "Budget 2026 kept the standard deduction under new regime at ₹75,000 (increased from ₹50,000 in Budget 2024)."),
    _mcq("I3", 4, ["GST", "Time of Supply"],
         "For services under forward charge (excluding continuous supply), the time of supply under Sec 13 CGST is:",
         {"A": "Date of invoice issue (if within 30 days) or date of provision, whichever earlier", "B": "Date of receipt of payment always", "C": "Date of contract", "D": "Last day of the tax period"},
         "A", "Sec 13(2)(a): earlier of (i) date of invoice if issued within 30 days of provision, else date of provision, OR (ii) date of receipt of payment."),
    _mcq("I3", 3, ["Capital Gains", "Direct Tax"],
         "Sec 54F exemption on LTCG from sale of non-residential capital asset is available when:",
         {"A": "The taxpayer owns no other residential house on the date of transfer", "B": "The taxpayer owns not more than 1 residential house other than the new one", "C": "The taxpayer is an individual or HUF only", "D": "Both B and C"},
         "D", "Sec 54F requires the assessee to be individual/HUF and, on the date of transfer, to not own more than 1 residential house (other than the new one)."),
    _mcq("I3", 2, ["GST", "Invoice"],
         "Under GST, e-invoicing is mandatory for taxpayers with aggregate turnover exceeding (post 01-Aug-2026):",
         {"A": "₹100 crore", "B": "₹50 crore", "C": "₹10 crore", "D": "₹3 crore"},
         "D", "CBIC Notification 18/2026-CT reduced the e-invoicing threshold from ₹5 crore to ₹3 crore w.e.f. 01-Aug-2026 with 90-day grace period."),
    _mcq("I3", 3, ["Income from Other Sources", "Direct Tax"],
         "Under Sec 56(2)(x), gift of money exceeding ₹50,000 in aggregate during the FY from a non-relative is:",
         {"A": "Fully exempt", "B": "Taxable as 'Income from Other Sources'", "C": "Taxable only if from an unregistered charity", "D": "Exempt up to ₹2,00,000"},
         "B", "Sec 56(2)(x): if aggregate money received without consideration from non-relatives exceeds ₹50,000 in FY, the entire amount is taxable as IFOS."),
    _mcq("I3", 4, ["Set off C/f", "Direct Tax"],
         "Loss under head 'Capital Gains' (LT) can be set off against:",
         {"A": "Any head in the same year", "B": "Only LTCG in the same year and following 8 AYs", "C": "STCG or LTCG in the same year and 8 AYs", "D": "Any head except salary"},
         "B", "Sec 74: LTCL can only be set off against LTCG in the same AY and c/f for 8 AYs against LTCG only. STCL can be set off against STCG or LTCG."),
    _mcq("I3", 2, ["GST", "Composition"],
         "The composition scheme under Sec 10 CGST is available to a manufacturer with turnover up to:",
         {"A": "₹50 lakh", "B": "₹75 lakh", "C": "₹1 crore", "D": "₹1.5 crore"},
         "D", "Sec 10: composition threshold — ₹1.5 crore for manufacturers/traders; ₹50 lakh for service providers (per Sec 10(2A))."),
    _q("I3", "subjective", 4, ["Capital Gains", "Direct Tax"],
       "Mr. X purchased a house on 01-Apr-2010 for ₹40 lakh. He sells it on 15-Jun-2026 for ₹1.5 crore. Indexed cost of acquisition using CII 2010-11 = 167, CII 2026-27 = 348. Compute LTCG assuming no exemption is claimed.",
       None, None,
       "Indexed COA = 40 × (348/167) = ₹83,35,329.\nLTCG = ₹1,50,00,000 - ₹83,35,329 = ₹66,64,671.\nTax @ 12.5% under Sec 112 (long-term other than listed equity) = ₹8,33,084 (with indexation) OR 20% without indexation option is not available for immovable property post Budget 2024. Add applicable surcharge + cess.",
       marks=8, neg=0),
    _mcq("I3", 3, ["Advance Tax", "Direct Tax"],
         "The last date for payment of the fourth (final) instalment of advance tax for an individual is:",
         {"A": "15-Mar of the FY", "B": "31-Mar of the FY", "C": "15-Jun of the AY", "D": "31-Jul of the AY"},
         "A", "Sec 211: 4th instalment (100% of advance tax) due 15-March of the FY. Then the balance is payable by way of self-assessment tax under Sec 140A."),
]

# ====== I4 COSTING (15) ======
I4_QUESTIONS = [
    _mcq("I4", 2, ["Material Cost"],
         "The Economic Order Quantity (EOQ) formula is:",
         {"A": "√(2 × A × O / C)", "B": "A × O / C", "C": "√(A × C / O)", "D": "(A + O) / C"},
         "A", "EOQ = √(2AO/C) where A = annual demand, O = ordering cost per order, C = carrying cost per unit per year."),
    _mcq("I4", 3, ["Overheads", "Absorption Costing"],
         "Under-absorption of factory overheads is typically disposed of by:",
         {"A": "Debiting Costing P&L account", "B": "Supplementary rate method or writing off to Costing P&L", "C": "Adding to WIP inventory", "D": "Crediting to next year's overhead account"},
         "B", "Under/over-absorption can be treated by (i) supplementary rate applied to units in inventory and cost of sales, or (ii) transferred to Costing P&L."),
    _mcq("I4", 4, ["Standard Costing", "Variance Analysis"],
         "Material Usage Variance = ",
         {"A": "(Standard Qty for Actual Output - Actual Qty) × Standard Rate", "B": "(Actual Qty - Standard Qty) × Actual Rate", "C": "(Std Rate - Actual Rate) × Std Qty", "D": "None"},
         "A", "MUV = SR × (SQ for actual output - AQ). Difference between what standard quantity should have been for actual output vs. actual quantity used, priced at standard rate."),
    _mcq("I4", 3, ["Marginal Costing", "CVP"],
         "P/V ratio × Sales = ",
         {"A": "Fixed Cost", "B": "Contribution", "C": "Profit", "D": "Break-even Sales"},
         "B", "P/V Ratio = Contribution/Sales. Therefore P/V Ratio × Sales = Contribution."),
    _mcq("I4", 4, ["Process Costing"],
         "Equivalent units in a process are computed to:",
         {"A": "Include only completed units", "B": "Convert partially completed units to equivalent completed units", "C": "Only for joint products", "D": "Compute EOQ"},
         "B", "Equivalent production converts partially-completed WIP into 'equivalent completed units' based on % completion, so cost per unit can be computed uniformly."),
    _mcq("I4", 2, ["Marginal Costing"],
         "Break-Even Point (in units) = ",
         {"A": "Fixed Cost / Contribution per unit", "B": "Sales / Contribution", "C": "Total Cost / Selling Price", "D": "Profit × P/V Ratio"},
         "A", "BEP (units) = Fixed Cost ÷ Contribution per unit. This is the number of units to sell to cover all fixed costs."),
    _mcq("I4", 3, ["Budget", "Budgetary Control"],
         "A budget which is designed to change according to activity level is called:",
         {"A": "Rolling budget", "B": "Flexible budget", "C": "Zero-based budget", "D": "Cash budget"},
         "B", "A flexible budget adjusts amounts based on actual activity level (units produced/sold) — providing a fair comparison for variance analysis."),
    _mcq("I4", 4, ["Activity Based Costing"],
         "Under ABC, the cost driver for the activity 'setting up machines' would typically be:",
         {"A": "Machine hours", "B": "Direct labour hours", "C": "Number of setups", "D": "Sales revenue"},
         "C", "In ABC, the cost driver should have a cause-and-effect relationship with the activity. For 'setup' activity, number of setups is the direct driver."),
    _mcq("I4", 3, ["Standard Costing"],
         "Labour Efficiency Variance is favourable when:",
         {"A": "Actual hours < Standard hours for actual output", "B": "Actual rate > Standard rate", "C": "Actual output < Standard output", "D": "Idle time is high"},
         "A", "LEV = SR × (SH for actual output - AH). Favourable when actual hours are less than the standard hours allowed."),
    _mcq("I4", 3, ["Overheads"],
         "The primary distinction between production overheads and administrative overheads is:",
         {"A": "Amount", "B": "Whether they relate to production or non-production functions", "C": "Whether they are fixed or variable", "D": "Whether they are direct or indirect"},
         "B", "Production overheads: indirect costs of manufacturing (factory rent, indirect labour). Admin overheads: costs of admin function (office rent, admin salaries)."),
    _mcq("I4", 4, ["Marginal Costing", "Decision Making"],
         "A company has surplus capacity. A special order at a price below normal is considered. Which cost is relevant?",
         {"A": "Full absorbed cost", "B": "Total variable cost only (with no capacity constraint)", "C": "Total cost + normal margin", "D": "Prime cost"},
         "B", "Special order analysis uses incremental (variable) cost when there is idle capacity. Fixed costs are irrelevant (sunk). Accept if selling price > incremental cost + opportunity cost."),
    _mcq("I4", 3, ["Contract Costing"],
         "In contract accounts, notional profit is transferred to P&L based on which of these formulas (when contract is between 25% and 50% complete)?",
         {"A": "Notional Profit × 1/3 × (Cash Received / Work Certified)", "B": "Notional Profit × 2/3", "C": "Full notional profit", "D": "None"},
         "A", "Standard rule: when 25-50% complete, transfer 1/3 × Notional Profit × (Cash Received / Work Certified) to P&L. Above 50%, use 2/3 factor."),
    _mcq("I4", 3, ["Standard Costing"],
         "Which of the following is NOT a component of Material Cost Variance?",
         {"A": "Material Price Variance", "B": "Material Usage Variance", "C": "Material Efficiency Variance", "D": "Material Mix Variance"},
         "C", "Material Cost Variance = Price Variance + Usage Variance. Usage Variance is further split into Mix + Yield Variance. 'Material Efficiency Variance' is a labour term, not material."),
    _q("I4", "subjective", 4, ["Marginal Costing"],
       "A product has: SP = ₹500, VC = ₹300, FC = ₹80,000/month. (a) Compute BEP in units and value. (b) Compute Margin of Safety if sales are 500 units. (c) What sales are needed to earn a profit of ₹40,000/month?",
       None, None,
       "Contribution/unit = 500-300 = ₹200. P/V Ratio = 40%.\n(a) BEP units = 80,000/200 = 400 units. BEP value = 400 × 500 = ₹2,00,000.\n(b) MoS = Actual Sales - BEP Sales = (500-400) × 500 = ₹50,000, i.e. 20% of sales.\n(c) Sales for target profit = (FC + Profit)/CM ratio = (80,000+40,000)/0.4 = ₹3,00,000 = 600 units.",
       marks=6, neg=0),
    _mcq("I4", 2, ["Employee Cost"],
         "Under the Halsey premium plan, the worker is guaranteed:",
         {"A": "50% of time saved as bonus, on top of base wages", "B": "The whole time saved", "C": "Only piece-rate wages", "D": "Weekly bonus"},
         "A", "Halsey Premium: Total wages = Time taken × Rate + 50% × Time saved × Rate. Guaranteed time-rate + bonus for time saved."),
]

# ====== I5 AUDITING (12) ======
I5_QUESTIONS = [
    _mcq("I5", 2, ["Nature of Audit"],
         "The primary objective of an independent financial statement audit is to:",
         {"A": "Detect all fraud", "B": "Express an opinion on whether the FS give a true and fair view", "C": "Certify absolute accuracy", "D": "Advise management on tax"},
         "B", "SA 200: auditor's primary objective is to obtain reasonable assurance and express an opinion on whether the FS are prepared, in all material respects, in accordance with the applicable financial reporting framework."),
    _mcq("I5", 3, ["Audit Documentation"],
         "Audit documentation should be assembled in the final audit file within:",
         {"A": "30 days after issuance of audit report", "B": "60 days after issuance of audit report", "C": "90 days after year-end", "D": "6 months"},
         "B", "SQC 1 / SA 230: assembly of audit file should be within 60 days after the date of the auditor's report."),
    _mcq("I5", 4, ["Audit Report", "CARO"],
         "Under CARO 2020, which of the following clauses is NOT applicable to a company?",
         {"A": "Loans to related parties (Sec 189)", "B": "Compliance with SEBI takeover code", "C": "Whistle-blower mechanism", "D": "Physical verification of inventory"},
         "B", "CARO 2020 has 21 specific clauses. SEBI takeover code compliance is a separate LODR obligation, not in CARO. A, C, D are all covered clauses."),
    _mcq("I5", 3, ["Fraud", "Auditor Responsibility"],
         "Under Sec 143(12) of the Companies Act, the auditor must report fraud to the Central Government if fraud amount is:",
         {"A": "> ₹1 crore", "B": "> ₹10 lakh", "C": "> ₹5 crore", "D": "Any fraud"},
         "A", "Rule 13 of Companies (Audit and Auditors) Rules 2014: report to Central Government via Form ADT-4 if fraud ≥ ₹1 crore. Lower amounts reported to the Board / Audit Committee."),
    _mcq("I5", 2, ["Internal Control"],
         "The 5 components of internal control per SA 315 include all of the following EXCEPT:",
         {"A": "Control environment", "B": "Risk assessment process", "C": "Information system", "D": "External audit"},
         "D", "SA 315 lists: (1) control environment, (2) risk assessment process, (3) information system, (4) control activities, (5) monitoring. External audit is not a component of internal control."),
    _mcq("I5", 3, ["Audit Evidence"],
         "Which of the following is generally the MOST reliable audit evidence?",
         {"A": "Documentary evidence obtained directly from a third party", "B": "Client's verbal representation", "C": "Photocopies of contracts provided by client", "D": "Analytical procedures"},
         "A", "SA 500: external evidence obtained directly by the auditor (e.g., bank confirmation letter) is more reliable than internal/client-provided evidence."),
    _mcq("I5", 4, ["Audit Report"],
         "A qualified opinion is expressed when misstatements are:",
         {"A": "Material but not pervasive", "B": "Material and pervasive", "C": "Immaterial", "D": "Non-existent"},
         "A", "SA 705: Qualified — material but not pervasive. Adverse — material AND pervasive. Disclaimer — inability to obtain sufficient audit evidence that is material AND pervasive."),
    _mcq("I5", 3, ["Sampling"],
         "Statistical sampling differs from non-statistical sampling primarily in:",
         {"A": "Sample size", "B": "Use of probability theory to measure sampling risk", "C": "Type of population", "D": "Nature of tests"},
         "B", "Statistical sampling uses probability theory (random selection, quantified sampling risk); non-statistical uses professional judgment. Both may achieve reliable results if properly designed."),
    _mcq("I5", 2, ["Ethics"],
         "Independence of the auditor is threatened by:",
         {"A": "Self-review threat", "B": "Familiarity threat", "C": "Intimidation threat", "D": "All of the above"},
         "D", "IESBA/ICAI Code lists five threats: self-interest, self-review, advocacy, familiarity, intimidation. All impair independence in different ways."),
    _mcq("I5", 3, ["Analytical Procedures"],
         "Analytical procedures are required to be performed at which stages of the audit?",
         {"A": "Planning only", "B": "Substantive procedures only", "C": "Planning and overall review; substantive is optional", "D": "Only final review"},
         "C", "SA 520: Analytical procedures are REQUIRED at (i) risk assessment (planning) stage and (ii) overall review at the end of audit. Substantive analytical procedures are optional/at auditor's discretion."),
    _mcq("I5", 4, ["Companies Audit"],
         "Under Sec 141 of the Companies Act, a person cannot be appointed as auditor of a company if he/she is:",
         {"A": "A relative of a director", "B": "Indebted to the company for more than ₹5 lakh", "C": "Holding any security in the company", "D": "All disqualifications above are applicable subject to specifics"},
         "D", "Sec 141(3) lists disqualifications: officer/employee, partner of officer/employee, relative holds security > ₹1 lakh, indebted to company > ₹5 lakh, etc."),
    _q("I5", "subjective", 4, ["Audit Planning"],
       "Explain the concept of 'materiality' as per SA 320. Distinguish between overall materiality, performance materiality, and specific materiality. How does materiality affect the audit strategy?",
       None, None,
       "Materiality per SA 320: misstatements are material if they could reasonably be expected to influence economic decisions of users.\n\nOverall materiality: judgement about the FS as a whole (typically 5% of PBT, 1% of turnover, or 1-2% of total assets).\nPerformance materiality: reduced amount (usually 50-75% of overall) used at execution level to leave a safety margin.\nSpecific materiality: for particular classes of transactions or disclosures where users' expectations differ.\n\nEffect on strategy: lower materiality → more procedures / larger samples / greater precision. Materiality is re-evaluated as audit progresses.",
       marks=8, neg=0),
]

# ====== P1 FINANCIAL REPORTING (12) ======
P1_QUESTIONS = [
    _mcq("P1", 3, ["Ind AS 115", "Revenue"],
         "Under Ind AS 115, a performance obligation is satisfied over time if:",
         {"A": "Customer simultaneously receives and consumes benefits, OR entity creates asset customer controls, OR asset has no alternative use and enforceable right to payment",
          "B": "Cash is received",
          "C": "Invoice is issued",
          "D": "Delivery is scheduled"},
         "A", "Ind AS 115.35: PO satisfied over time if any ONE of three criteria is met — else at a point in time."),
    _mcq("P1", 4, ["Ind AS 116", "Leases"],
         "A lessee's ROU asset is initially measured at:",
         {"A": "Fair value", "B": "Initial lease liability + prepayments - lease incentives + initial direct costs + estimated dismantling costs", "C": "Present value of minimum lease payments only", "D": "Undiscounted lease payments"},
         "B", "Ind AS 116.24: ROU initially = initial lease liability + prepaid lease payments + IDC + estimated dismantling/restoration costs − lease incentives received."),
    _mcq("P1", 3, ["Ind AS 12", "Deferred Tax"],
         "Deferred tax is recognised on temporary differences arising from:",
         {"A": "Only tax losses", "B": "All temporary differences except those covered by initial recognition exemption / goodwill", "C": "Only permanent differences", "D": "Cash-flow items"},
         "B", "Ind AS 12: recognise deferred tax on all taxable temporary differences EXCEPT initial recognition of goodwill and initial recognition of an asset/liability that is not a business combination and affects neither accounting nor taxable profit."),
    _mcq("P1", 4, ["Ind AS 103", "Business Combinations"],
         "Under Ind AS 103, contingent consideration in a business combination is:",
         {"A": "Always classified as equity", "B": "Measured at fair value at acquisition date; subsequent classification determines P&L vs equity treatment", "C": "Ignored", "D": "Deducted from goodwill"},
         "B", "Ind AS 103.39: contingent consideration measured at FV at acquisition. If classified as equity → not re-measured. If liability → re-measured at each reporting date through P&L."),
    _mcq("P1", 3, ["Ind AS 16", "PPE"],
         "The revaluation model under Ind AS 16 requires revaluations to be:",
         {"A": "Performed at each year-end mandatorily", "B": "Made with sufficient regularity that the carrying amount does not differ materially from FV", "C": "Once every 5 years", "D": "Only for land"},
         "B", "Ind AS 16.31: revaluations should be made with sufficient regularity to ensure that carrying amount does not differ materially from fair value at reporting date."),
    _mcq("P1", 3, ["Ind AS 36", "Impairment"],
         "Recoverable amount is:",
         {"A": "Higher of FV less costs of disposal, and value in use", "B": "Lower of two", "C": "Only FV", "D": "Only value in use"},
         "A", "Ind AS 36: Recoverable amount = HIGHER of (Fair Value − Costs of Disposal) and Value in Use. Compare against carrying amount to determine impairment loss."),
    _mcq("P1", 4, ["Ind AS 109", "Financial Instruments"],
         "The general approach for measuring expected credit losses (ECL) requires:",
         {"A": "12-month ECL if credit risk has not significantly increased since initial recognition; lifetime ECL otherwise", "B": "Only lifetime ECL", "C": "Only 12-month ECL", "D": "Loss allowance only when default occurs"},
         "A", "Ind AS 109 general model: Stage 1 (12-month ECL) for assets not experiencing SICR; Stage 2 (lifetime ECL, still performing); Stage 3 (lifetime ECL, credit-impaired)."),
    _mcq("P1", 4, ["Ind AS 110", "Consolidation"],
         "Control per Ind AS 110 exists when the investor has all of the following EXCEPT:",
         {"A": "Power over the investee", "B": "Exposure to variable returns", "C": "Ability to use power to affect returns", "D": "Ownership > 50% mandatorily"},
         "D", "Ind AS 110: Control = Power + Exposure to variable returns + Ability to affect. Ownership > 50% is often (but not always) indicative — control can exist below 50% (de facto)."),
    _mcq("P1", 3, ["Ind AS 33", "EPS"],
         "Basic EPS is computed as:",
         {"A": "Net profit / weighted-average shares outstanding", "B": "Net profit / closing shares outstanding", "C": "Total equity / shares", "D": "PBT / opening shares"},
         "A", "Ind AS 33: Basic EPS = (Profit attributable to ordinary shareholders) / (Weighted-average number of ordinary shares outstanding during the period)."),
    _mcq("P1", 4, ["Ind AS 116", "Leases"],
         "In a sale-and-leaseback where the transfer qualifies as a sale, the seller-lessee measures the ROU asset arising from the leaseback at:",
         {"A": "Fair value of the asset transferred", "B": "The proportion of previous carrying amount that relates to right of use retained", "C": "Zero", "D": "Full carrying amount"},
         "B", "Ind AS 116.100: ROU = proportion of previous carrying amount of the asset relating to the right of use retained. Gain/loss recognised only for rights transferred."),
    _mcq("P1", 3, ["Ind AS 8"],
         "A change in accounting estimate is applied:",
         {"A": "Retrospectively", "B": "Prospectively — from the date of change", "C": "Only after auditor approval", "D": "Only in a business combination"},
         "B", "Ind AS 8: change in accounting estimate is applied prospectively — from the period of change. Change in accounting policy is applied retrospectively (subject to impracticability exception)."),
    _q("P1", "subjective", 5, ["Ind AS 115", "Revenue"],
       "Alpha Ltd enters into a contract with Beta Ltd on 01-Apr-2026 to deliver two products: (a) a customised software (₹80L) and (b) 3 years of technical support (₹36L). Total contract price ₹100L (i.e., ₹16L bundle discount). Standalone selling prices: software ₹80L, support ₹40L (₹13.33L/year). (i) Identify performance obligations. (ii) Allocate transaction price. (iii) State when revenue is recognised.",
       None, None,
       "(i) POs: Software (distinct — customer can benefit + separately identifiable) and Support Services (distinct — customer benefits over time). Two POs.\n(ii) Transaction price: ₹100L. SSPs: Software ₹80L, Support ₹40L; total ₹120L. Bundle discount ₹20L allocated proportionally: Software gets ₹80/120 × 100 = ₹66.67L; Support gets ₹40/120 × 100 = ₹33.33L.\n(iii) Software (customised, no alt use, enforceable right to payment) — recognised OVER TIME using appropriate output/input method. Support — over time (customer receives and consumes benefits simultaneously) — recognised straight-line at ₹11.11L per year over 3 years.",
       marks=10, neg=0),
]

# ====== P4 DIRECT TAX (16) ======
P4_QUESTIONS = [
    _mcq("P4", 4, ["Transfer Pricing"],
         "Under Sec 92CA, transfer pricing audit is compulsory when the aggregate value of international transactions exceeds:",
         {"A": "₹15 crore", "B": "₹20 crore", "C": "₹1 crore (specified domestic)", "D": "No threshold — always applicable"},
         "A", "Rule 10B/CBDT threshold: TP audit mandatory when international transactions exceed ₹15 crore (or specified domestic > ₹20 crore). Actually the ₹15Cr threshold applies for reference to TPO by AO. Actual audit report Form 3CEB required if any international transaction exists."),
    _mcq("P4", 3, ["Non-Resident Taxation"],
         "Under Sec 6(1), an individual is a resident of India for a previous year if he/she is in India for:",
         {"A": "≥ 182 days in that PY, OR ≥ 60 days in that PY AND ≥ 365 days in preceding 4 PYs", "B": "≥ 182 days only", "C": "Any presence", "D": "180 days"},
         "A", "Sec 6(1): resident if (i) 182+ days in PY OR (ii) 60+ days in PY AND 365+ days in 4 preceding PYs. Second condition modified for certain persons (Indian citizens leaving for employment: 182 days threshold applies)."),
    _mcq("P4", 4, ["MAT"],
         "MAT under Sec 115JB is applicable at what rate on book profits for a company (post Budget 2026)?",
         {"A": "15%", "B": "18.5%", "C": "22%", "D": "25.17%"},
         "A", "Sec 115JB: MAT reduced to 15% of book profits (plus surcharge + cess). Effective rate ~17.16% including cess."),
    _mcq("P4", 3, ["Capital Gains", "Slump Sale"],
         "Under Sec 50B (Slump Sale), cost of acquisition of the undertaking is:",
         {"A": "Book value", "B": "Net worth (aggregate value of total assets - total liabilities of undertaking as per books, subject to specific adjustments)", "C": "Fair value", "D": "Original cost + indexation"},
         "B", "Sec 50B: Cost = Net Worth (asset - liabilities per books, subject to Rule 11UAE adjustments — depreciable assets at WDV, self-generated goodwill at zero, other assets at book value, revaluation reversed)."),
    _mcq("P4", 4, ["DTAA"],
         "Under Article 5 of a typical DTAA (India's model), a 'Permanent Establishment' includes:",
         {"A": "Only fixed place of business", "B": "Fixed place, project PE (usually > 6/12 months), agency PE, service PE",
          "C": "Only agency PE", "D": "Only office"},
         "B", "PE definition (Article 5 model) covers: fixed place (branch, office, factory), project PE (construction lasting > 6/12 months), service PE, agency PE (dependent agent with authority)."),
    _mcq("P4", 4, ["Search & Seizure"],
         "Time limit for completion of assessment in a search case under Sec 153A is:",
         {"A": "12 months from end of month of last authorisation", "B": "18 months (24 months if TP reference)", "C": "9 months", "D": "24 months from search date"},
         "B", "Sec 153B: 18 months from end of month of last authorisation (24 months if TP reference u/s 92CA)."),
    _mcq("P4", 3, ["Assessment Procedure"],
         "Under Sec 148 (Reassessment), notice can be issued within:",
         {"A": "3 years from end of relevant AY generally; 10 years if income escaped > ₹50L", "B": "6 years always", "C": "16 years for foreign asset", "D": "Both A and C"},
         "D", "Sec 149 (as amended): (i) up to 3 years from end of AY normally, (ii) up to 10 years if escaped income > ₹50L (asset/entry basis), (iii) up to 16 years for foreign asset cases."),
    _mcq("P4", 4, ["Assessment of Firms"],
         "For a partnership firm, salary/interest paid to a working partner is allowable under Sec 40(b) subject to conditions AND up to:",
         {"A": "Any amount", "B": "Slab: ₹3L or 90% of first ₹3L book profit + 60% of balance (whichever is lower); interest capped at 12% simple",
          "C": "50% of book profit", "D": "₹10L maximum"},
         "B", "Sec 40(b): Salary to working partner deductible up to (a) ₹1.5L or 90% of first ₹3L book profit whichever higher + (b) 60% of balance book profit. Interest to any partner: capped at 12% simple. Must be authorised by deed."),
    _mcq("P4", 3, ["Charitable Trusts"],
         "Under Sec 11, income of a charitable trust is exempt to the extent applied for charitable purposes in India — the minimum application requirement is:",
         {"A": "50%", "B": "75%", "C": "85%", "D": "100%"},
         "C", "Sec 11(1)(a): 85% of income must be applied for charitable purposes; balance 15% may be accumulated. Higher accumulation requires Form 10 filing with specific purpose statement."),
    _mcq("P4", 4, ["GAAR"],
         "GAAR (General Anti-Avoidance Rules) under Sec 95-102 are invoked when an arrangement is deemed:",
         {"A": "Ordinary business", "B": "An impermissible avoidance arrangement — creating tax benefit + one of four tainted elements", "C": "Any tax planning", "D": "Sham transaction only"},
         "B", "Sec 96: IAA = arrangement with main purpose to obtain tax benefit AND (i) not at arm's length OR (ii) misuse of Act OR (iii) lacks commercial substance OR (iv) not for bona fide purposes."),
    _mcq("P4", 3, ["Deductions"],
         "Sec 80JJAA — deduction for additional employee cost — is available at:",
         {"A": "50% of additional cost for 3 years", "B": "30% of additional employee cost for 3 years", "C": "100% for 5 years", "D": "10% for 5 years"},
         "B", "Sec 80JJAA: 30% of additional employee cost, allowed for 3 AYs (starting AY in which employment is provided). Subject to Sec 80JJAA(2) conditions (minimum wage, PF-registered employee, employment > 240 days)."),
    _mcq("P4", 4, ["International Tax"],
         "The Equalisation Levy (introduced 2016; amended 2020) applies at:",
         {"A": "6% on online advertisement services by non-resident to Indian resident", "B": "2% on e-commerce supply by non-resident e-commerce operator (till Aug 2024 — abolished thereafter)", "C": "Both A and B (Original 6% still in force; 2% abolished)", "D": "Only 20%"},
         "C", "EL 1.0 (2016): 6% on online ads services by NR to Indian resident — still in force. EL 2.0 (2020): 2% on e-commerce supply — abolished from 01-Aug-2024."),
    _mcq("P4", 3, ["TDS", "Sec 194R"],
         "Sec 194R — TDS on benefit/perquisite arising from business — applies at:",
         {"A": "10% if value > ₹20,000 in FY", "B": "5% if value > ₹1,00,000", "C": "20% flat", "D": "1% on any amount"},
         "A", "Sec 194R: TDS @ 10% on aggregate value of benefits/perquisites > ₹20,000 in FY provided in course of business. Introduced Budget 2022, refined in Budget 2026 to explicitly cover software licences and cloud credits."),
    _q("P4", "subjective", 5, ["Transfer Pricing"],
       "XYZ Ltd (India) provides IT-BPO services to its parent XYZ Inc (US). Turnover ₹120 crore. Determine the safe-harbour margin applicable for AY 2026-27 as per CBDT Notification 43/2026. Also state what alternate compliance option is available if the taxpayer does not opt for safe harbour.",
       None, None,
       "Per CBDT Notification 43/2026 (Rule 10TD): revised safe-harbour margins for IT-BPO sector effective AY 2026-27 to AY 2028-29 — Routine ITeS: 15%, KPO: 18%, Contract R&D: 17%.\n\nFor an IT-BPO (ITeS) segment: 15% mark-up on total operating cost.\n\nAlternative compliance: if safe harbour not opted, taxpayer must comply with regular TP documentation under Rule 10D and file Form 3CEB. Can also opt for Advance Pricing Agreement (APA) under Sec 92CC for future certainty.",
       marks=8, neg=0),
    _mcq("P4", 3, ["Assessment"],
         "The time limit for filing an appeal to CIT(Appeals) under Sec 246A is:",
         {"A": "30 days from service of notice of demand", "B": "60 days", "C": "90 days", "D": "6 months"},
         "A", "Sec 249(2): appeal must be filed within 30 days from date of service of notice of demand under Sec 156, or date of order in other cases. CIT(A) may condone delay for sufficient cause."),
    _mcq("P4", 4, ["Capital Gains"],
         "Under Sec 45(3), when a partner contributes a capital asset to a partnership firm, capital gains are computed using:",
         {"A": "FMV of asset", "B": "Amount recorded in the books of the firm", "C": "Original cost to partner", "D": "Book value in partner's books"},
         "B", "Sec 45(3): capital gains taxed in the year of transfer. Full value of consideration = amount recorded in the FIRM's books (not market value). Cost = partner's original cost with indexation."),
]

# ====== P5 IDT / GST (12) ======
P5_QUESTIONS = [
    _mcq("P5", 3, ["GST", "Value of Supply"],
         "Under Sec 15 CGST, the value of supply for GST is:",
         {"A": "Contract price only", "B": "Transaction value — the price actually paid/payable if parties are unrelated + specified inclusions",
          "C": "Fair market value always", "D": "MRP"},
         "B", "Sec 15(1): value of supply = transaction value (price actually paid/payable) provided parties are unrelated and price is sole consideration. Sec 15(2) lists inclusions: taxes (other than GST), incidental expenses, interest on delayed payment, subsidies (except govt), etc."),
    _mcq("P5", 4, ["GST", "Input Tax Credit"],
         "Under Sec 17(5), which of the following ITC is NOT blocked?",
         {"A": "Motor vehicle used for further supply of such vehicles", "B": "Food and beverages", "C": "Membership of a club", "D": "Rent-a-cab services for personal use"},
         "A", "Sec 17(5): motor vehicles ARE blocked EXCEPT when used for (i) further supply of vehicles, (ii) transportation of passengers/goods, (iii) imparting training. Options B, C, D are all blocked."),
    _mcq("P5", 3, ["GST", "Returns"],
         "GSTR-9 (Annual Return) is required for taxpayers with aggregate turnover exceeding:",
         {"A": "₹1 crore", "B": "₹2 crore", "C": "₹5 crore", "D": "₹10 crore"},
         "B", "Rule 80: GSTR-9 mandatory for taxpayers with turnover > ₹2 crore. Below ₹2 crore is optional. GSTR-9C (reconciliation) threshold raised to ₹10 crore per Budget 2026."),
    _mcq("P5", 4, ["Customs"],
         "Under Sec 14 of the Customs Act, transaction value for imported goods includes all of the following EXCEPT:",
         {"A": "Cost of packing", "B": "Design & engineering charges (undertaken outside India)", "C": "Freight cost", "D": "Buying commission paid by importer to Indian buying agent"},
         "D", "Sec 14 + Customs Valuation Rules: buying commissions (paid to importer's own buying agent) are EXCLUDED from CIF value. Packing, freight up to Indian port, design/engineering (subject to conditions) are included."),
    _mcq("P5", 3, ["GST", "Refund"],
         "Under Sec 54, application for GST refund is to be filed within:",
         {"A": "6 months from relevant date", "B": "1 year", "C": "2 years from relevant date", "D": "3 years"},
         "C", "Sec 54(1): refund application within 2 years from the relevant date (defined in Explanation to Sec 54). For inverted duty refund, from due date of GSTR-3B."),
    _mcq("P5", 4, ["GST", "Supply"],
         "A supply between two branches of the same legal entity (with separate GSTINs) in different states is:",
         {"A": "Not a supply", "B": "A taxable supply between distinct persons under Schedule I", "C": "Exempt", "D": "Composite supply"},
         "B", "Sec 25(4): different registrations of a person are treated as distinct persons. Schedule I para 2: supply of goods/services between distinct persons in the course/furtherance of business is a supply even without consideration."),
    _mcq("P5", 3, ["GST", "Reverse Charge"],
         "Under Sec 9(3) CGST, reverse charge on legal services provided by an advocate to a business entity applies when:",
         {"A": "Business entity is in specified category and turnover > threshold; RCM at 18%", "B": "Never", "C": "Only for individual clients", "D": "Only for LLP clients"},
         "A", "Notification 13/2017-CT(Rate): legal services by an advocate or firm of advocates to a business entity (aggregate turnover > ₹20L/₹40L) are under RCM. Rate 18%. Government departments also covered."),
    _mcq("P5", 4, ["Customs", "FTP"],
         "Under the Foreign Trade Policy 2023 (amended), the EPCG scheme now requires an export obligation of (per FY 2026):",
         {"A": "5x duty saved over 6 years", "B": "6x duty saved with block-wise EO", "C": "8x always", "D": "4x for MSMEs only"},
         "B", "DGFT Public Notice 15/2026 tightened EPCG EO to 6x duty saved (from 5x) with block-wise export obligation."),
    _mcq("P5", 3, ["GST", "Time of Supply"],
         "Time of supply of goods under RCM (Sec 12(3)) is the earliest of:",
         {"A": "Date of receipt of goods, date of payment (books), or 30 days from invoice date", "B": "Date of invoice only", "C": "Date of contract", "D": "First day of the tax period"},
         "A", "Sec 12(3): earliest of (i) date of receipt, (ii) date of payment (as per books OR debit in bank), (iii) 30 days from date of invoice (60 days for services)."),
    _mcq("P5", 4, ["GST", "Appeals"],
         "First appeal against an adjudication order under GST is filed under Sec 107 within:",
         {"A": "30 days", "B": "3 months (extendable 1 month)", "C": "6 months", "D": "1 year"},
         "B", "Sec 107: 3 months from communication of order (extendable by another 1 month by Appellate Authority on sufficient cause). Deposit of admitted tax + 10% of disputed tax (subject to ₹20/25 cr cap) required."),
    _mcq("P5", 3, ["GST", "Composition"],
         "Under Sec 10(2A), a services provider can opt for composition levy if aggregate turnover in preceding FY did not exceed:",
         {"A": "₹20 lakh", "B": "₹50 lakh", "C": "₹1 crore", "D": "₹1.5 crore"},
         "B", "Sec 10(2A) — special composition scheme for services (or mixed supply of goods and services) up to ₹50 lakh turnover. Rate 6% (3% CGST + 3% SGST)."),
    _q("P5", "subjective", 5, ["GST", "Input Tax Credit"],
       "M/s ABC Ltd purchased inputs worth ₹10,00,000 (GST @ 18% = ₹1,80,000) in June 2026. It also availed input services worth ₹2,00,000 (GST @ 18% = ₹36,000) — including ₹50,000 (GST ₹9,000) spent on employee outdoor catering. It has outward tax liability of ₹2,50,000 for June. Compute ITC eligible and net cash payable.",
       None, None,
       "ITC on inputs: ₹1,80,000 (fully eligible — inputs used in business).\nITC on input services: ₹36,000 - ₹9,000 (outdoor catering BLOCKED under Sec 17(5)(b)(i)) = ₹27,000.\nTotal eligible ITC = ₹1,80,000 + ₹27,000 = ₹2,07,000.\nOutward liability = ₹2,50,000.\nNet cash payable = ₹2,50,000 - ₹2,07,000 = ₹43,000.\n(Assume all invoices reflected in GSTR-2B, so Sec 16 ITC conditions satisfied.)",
       marks=6, neg=0),
]

# ====== F2 BUSINESS LAWS (10) ======
F2_QUESTIONS = [
    _mcq("F2", 1, ["Contract Act"],
         "Under Sec 2(h) of the Indian Contract Act, a contract is:",
         {"A": "An agreement", "B": "A promise", "C": "An agreement enforceable by law", "D": "A proposal"},
         "C", "Sec 2(h): Contract = Agreement enforceable by law. Not every agreement is a contract; enforceability is the additional element."),
    _mcq("F2", 2, ["Contract Act", "Consideration"],
         "Under Sec 25, an agreement without consideration is valid when:",
         {"A": "Made in writing and registered, out of natural love and affection between parties standing in near relation",
          "B": "Between friends", "C": "In business relationships", "D": "Never"},
         "A", "Sec 25 exceptions: (1) natural love + writing + registered + near relation; (2) compensation for past voluntary services; (3) promise to pay time-barred debt in writing; (4) gift completed (Sec 25(2))."),
    _mcq("F2", 2, ["Contract Act", "Free Consent"],
         "Consent is 'free' under Sec 14 when NOT caused by:",
         {"A": "Coercion, undue influence, fraud, misrepresentation, mistake", "B": "Consideration",
          "C": "Registration", "D": "Legal object"},
         "A", "Sec 14: consent is free when not caused by (i) coercion, (ii) undue influence, (iii) fraud, (iv) misrepresentation, or (v) mistake subject to Sec 20/21/22."),
    _mcq("F2", 3, ["Sale of Goods Act"],
         "Under Sec 20 of Sale of Goods Act, when unascertained goods are sold, property passes when:",
         {"A": "Contract is made", "B": "Goods are ascertained and unconditionally appropriated to the contract with assent of the other party", "C": "Price is paid", "D": "Delivery is made"},
         "B", "Sec 23: property passes on unconditional appropriation with assent (which may be prior or subsequent) of the other party. Ascertainment is a prerequisite (Sec 18)."),
    _mcq("F2", 2, ["Partnership Act"],
         "Under Sec 4 of the Indian Partnership Act, 1932, partnership is:",
         {"A": "Relation between persons who agree to share profits of business carried on by all or any of them acting for all",
          "B": "Any joint business", "C": "Association of persons", "D": "Only registered firm"},
         "A", "Sec 4: Partnership = relation between persons who have agreed to share the profits of a business carried on by all OR any of them acting for all. Mutual agency is the true test."),
    _mcq("F2", 3, ["LLP Act"],
         "Under the LLP Act 2008, minimum number of designated partners in an LLP is:",
         {"A": "1", "B": "2 (at least one Indian resident)", "C": "3", "D": "5"},
         "B", "Sec 7 LLP Act: Every LLP shall have at least 2 designated partners. At least 1 must be a resident of India (i.e., stayed in India for at least 120 days in the FY)."),
    _mcq("F2", 3, ["Companies Act"],
         "Under Sec 2(85) of the Companies Act, 2013, a Small Company is one whose paid-up capital is up to:",
         {"A": "₹50 lakh and turnover up to ₹2 crore",
          "B": "₹4 crore paid-up capital AND turnover up to ₹40 crore (2022 amendment)",
          "C": "₹10 crore", "D": "₹1 crore"},
         "B", "Sec 2(85) as amended by 2022 notification: paid-up capital up to ₹4 crore AND turnover up to ₹40 crore. Both conditions must be satisfied. Excludes public companies, holding/subsidiary of any co., Sec 8 co., statutory co."),
    _mcq("F2", 2, ["Negotiable Instruments"],
         "Under Sec 4 of the Negotiable Instruments Act, 1881, a promissory note requires:",
         {"A": "An unconditional undertaking, in writing, signed by the maker, to pay a certain sum of money only to (or to the order of) a certain person",
          "B": "Verbal promise", "C": "Bank guarantee only", "D": "Cheque format"},
         "A", "Sec 4: PN must contain an unconditional UNDERTAKING (not order), in writing, signed by the maker, to pay a certain sum of MONEY ONLY, to a certain person or to bearer."),
    _mcq("F2", 3, ["Contract Act", "Discharge"],
         "A contract may be discharged by:",
         {"A": "Performance", "B": "Breach", "C": "Impossibility of performance (Sec 56)", "D": "All of the above"},
         "D", "Discharge of contracts: (1) performance, (2) mutual agreement (novation, alteration, rescission, remission), (3) impossibility (Sec 56), (4) lapse of time (Limitation), (5) operation of law, (6) breach."),
    _mcq("F2", 2, ["Contract Act", "Capacity"],
         "Under Sec 11 of the Indian Contract Act, a minor's contract is:",
         {"A": "Voidable at the option of the minor", "B": "Void ab initio", "C": "Valid if for necessaries",
          "D": "Void ab initio, but the minor may be liable for necessaries supplied under Sec 68"},
         "D", "Mohori Bibee v Dharmodas Ghose (1903): a minor's contract is void ab initio. But Sec 68 makes minor's ESTATE (not personally) liable for reimbursement of necessaries supplied to him."),
]

ALL_QUESTIONS = (
    I3_QUESTIONS + I4_QUESTIONS + I5_QUESTIONS + P1_QUESTIONS
    + P4_QUESTIONS + P5_QUESTIONS + F2_QUESTIONS
)


def _pick_ids(questions, n):
    """Return question_ids of first n. If fewer available, cycles to reach n."""
    ids = [q["question_id"] for q in questions]
    if len(ids) >= n:
        return ids[:n]
    # If insufficient, repeat (allowed in seed since it's illustrative)
    out = []
    i = 0
    while len(out) < n:
        out.append(ids[i % len(ids)])
        i += 1
    return out


MOCK_TESTS = [
    {
        "mock_id": "mock_i3_tax_full", "paper_code": "I3", "title": "Intermediate Taxation — Full Paper",
        "duration_minutes": 90, "total_marks": 100, "difficulty_profile": "balanced",
        "question_ids": [q["question_id"] for q in I3_QUESTIONS] + [q["question_id"] for q in I5_QUESTIONS[:10]],
        "attempts_count": 0,
    },
    {
        "mock_id": "mock_i3_tax_speed", "paper_code": "I3", "title": "Taxation — Speed Round",
        "duration_minutes": 20, "total_marks": 30, "difficulty_profile": "easy",
        "question_ids": _pick_ids([q for q in I3_QUESTIONS if q["type"] == "mcq"], 15),
        "attempts_count": 0,
    },
    {
        "mock_id": "mock_i4_costing", "paper_code": "I4", "title": "Cost & Management Accounting — Full",
        "duration_minutes": 60, "total_marks": 60, "difficulty_profile": "balanced",
        "question_ids": [q["question_id"] for q in I4_QUESTIONS] + _pick_ids(I3_QUESTIONS[:5], 5),
        "attempts_count": 0,
    },
    {
        "mock_id": "mock_i5_audit", "paper_code": "I5", "title": "Auditing & Ethics — Hard",
        "duration_minutes": 60, "total_marks": 60, "difficulty_profile": "hard",
        "question_ids": [q["question_id"] for q in I5_QUESTIONS] + _pick_ids(I3_QUESTIONS[:13], 13),
        "attempts_count": 0,
    },
    {
        "mock_id": "mock_p1_fr", "paper_code": "P1", "title": "Financial Reporting — Ind AS Deep Dive",
        "duration_minutes": 120, "total_marks": 100, "difficulty_profile": "hard",
        "question_ids": [q["question_id"] for q in P1_QUESTIONS] + _pick_ids(P4_QUESTIONS[:13], 13),
        "attempts_count": 0,
    },
    {
        "mock_id": "mock_p4_dt", "paper_code": "P4", "title": "Direct Tax Laws & International Tax — Full",
        "duration_minutes": 90, "total_marks": 90, "difficulty_profile": "balanced",
        "question_ids": [q["question_id"] for q in P4_QUESTIONS] + _pick_ids(P1_QUESTIONS[:14], 14),
        "attempts_count": 0,
    },
    {
        "mock_id": "mock_p5_idt_gst", "paper_code": "P5", "title": "Indirect Tax (GST + Customs)",
        "duration_minutes": 75, "total_marks": 75, "difficulty_profile": "balanced",
        "question_ids": [q["question_id"] for q in P5_QUESTIONS] + _pick_ids(I3_QUESTIONS[5:18], 13),
        "attempts_count": 0,
    },
    {
        "mock_id": "mock_f2_bl", "paper_code": "F2", "title": "Foundation Business Laws — Warm-up",
        "duration_minutes": 45, "total_marks": 50, "difficulty_profile": "easy",
        "question_ids": [q["question_id"] for q in F2_QUESTIONS] + _pick_ids(I3_QUESTIONS[:10], 10),
        "attempts_count": 0,
    },
]
