"""Phase 4 syllabus seed — ICAI 2026 chapter structure with weightages.

Chapter names use canonical ICAI paper titles. Weightages are historical
approximations that sum to ~100% per paper. estimated_hours are rough for
first-pass reading + revision (3-15h per chapter).
"""
import uuid


def _chap(n, name, hours, wt):
    """Chapter builder."""
    return {
        "chapter_id": f"ch_{uuid.uuid4().hex[:10]}",
        "number": n,
        "name": name,
        "estimated_hours": hours,
        "weightage_pct": wt,
    }


# ----------------------- FOUNDATION -----------------------
F1_CHAPTERS = [  # Principles and Practice of Accounting — 10
    _chap(1, "Theoretical Framework of Accounting", 6, 8),
    _chap(2, "Accounting Process (Journal, Ledger, Trial Balance)", 10, 12),
    _chap(3, "Bank Reconciliation Statement", 5, 6),
    _chap(4, "Inventories (AS-2)", 6, 8),
    _chap(5, "Depreciation & Amortisation (AS-6/10)", 6, 8),
    _chap(6, "Bills of Exchange & Promissory Notes", 5, 6),
    _chap(7, "Preparation of Financial Statements (Sole Proprietor)", 10, 14),
    _chap(8, "Partnership Accounts (Admission, Retirement, Dissolution)", 12, 18),
    _chap(9, "Company Accounts — Introduction & Share Capital", 10, 12),
    _chap(10, "Not-for-Profit Organisation Accounts", 6, 8),
]
F2_CHAPTERS = [  # Business Laws + BCR — 8
    _chap(1, "Indian Contract Act, 1872", 12, 20),
    _chap(2, "Sale of Goods Act, 1930", 6, 10),
    _chap(3, "Indian Partnership Act, 1932", 6, 10),
    _chap(4, "Limited Liability Partnership Act, 2008", 4, 6),
    _chap(5, "Companies Act, 2013 — Preliminary", 6, 10),
    _chap(6, "Negotiable Instruments Act, 1881", 5, 8),
    _chap(7, "Business Communication & Correspondence", 6, 20),
    _chap(8, "Report Writing & Precis Writing", 5, 16),
]
F3_CHAPTERS = [  # Quant, LR, Stats — 12
    _chap(1, "Ratio & Proportion, Indices, Logarithms", 5, 6),
    _chap(2, "Equations (Linear, Quadratic, Cubic)", 5, 6),
    _chap(3, "Linear Inequalities", 4, 4),
    _chap(4, "Time Value of Money", 6, 10),
    _chap(5, "Permutations & Combinations", 6, 8),
    _chap(6, "Sequence & Series (AP, GP)", 5, 6),
    _chap(7, "Sets, Relations, Functions", 5, 6),
    _chap(8, "Basic Concepts of Calculus", 6, 8),
    _chap(9, "Number Series, Coding-Decoding, Directions", 6, 12),
    _chap(10, "Statistical Description of Data", 8, 12),
    _chap(11, "Measures of Central Tendency & Dispersion", 8, 12),
    _chap(12, "Probability, Correlation & Regression", 10, 10),
]
F4_CHAPTERS = [  # Business Economics + BCK — 10
    _chap(1, "Nature & Scope of Business Economics", 4, 6),
    _chap(2, "Theory of Demand & Supply", 8, 12),
    _chap(3, "Theory of Production & Cost", 8, 12),
    _chap(4, "Meaning & Types of Markets", 6, 10),
    _chap(5, "Business Cycles", 4, 6),
    _chap(6, "Determination of National Income", 6, 8),
    _chap(7, "Public Finance & Fiscal Policy", 6, 10),
    _chap(8, "Money & Banking", 6, 10),
    _chap(9, "International Trade & Balance of Payments", 6, 12),
    _chap(10, "Indian Economy & Business Environment", 6, 14),
]

# ----------------------- INTERMEDIATE -----------------------
I1_CHAPTERS = [  # Advanced Accounting — 14 (renumbered from prompt's INT1)
    _chap(1, "Framework for Preparation of Financial Statements", 4, 4),
    _chap(2, "Applicability of Accounting Standards", 4, 4),
    _chap(3, "Ind AS 1 — Presentation of Financial Statements", 6, 6),
    _chap(4, "Ind AS 2 — Inventories", 5, 5),
    _chap(5, "Ind AS 16 — Property, Plant & Equipment", 8, 8),
    _chap(6, "Ind AS 115 — Revenue from Contracts", 10, 10),
    _chap(7, "Ind AS 116 — Leases", 8, 8),
    _chap(8, "Ind AS 12 — Income Taxes (Deferred Tax)", 8, 8),
    _chap(9, "Employee Benefits (Ind AS 19)", 6, 6),
    _chap(10, "Financial Instruments (Ind AS 109/32/107)", 12, 12),
    _chap(11, "Business Combinations & Consolidation (Ind AS 103/110)", 15, 14),
    _chap(12, "Investment Property (Ind AS 40)", 4, 4),
    _chap(13, "Foreign Currency Transactions (Ind AS 21)", 6, 6),
    _chap(14, "Cash Flow Statements & EPS", 6, 5),
]
I2_CHAPTERS = [  # Corporate & Other Laws — 12
    _chap(1, "Preliminary — Companies Act, 2013 (Sec 1-2)", 4, 4),
    _chap(2, "Incorporation of Company & Matters Incidental", 6, 8),
    _chap(3, "Prospectus & Allotment of Securities", 6, 8),
    _chap(4, "Share Capital & Debentures", 8, 10),
    _chap(5, "Acceptance of Deposits by Companies", 4, 6),
    _chap(6, "Registration of Charges", 4, 6),
    _chap(7, "Management & Administration (AGM, Board Meetings)", 8, 12),
    _chap(8, "Declaration & Payment of Dividend", 5, 8),
    _chap(9, "Accounts of Companies", 6, 10),
    _chap(10, "Audit & Auditors", 6, 8),
    _chap(11, "General Clauses Act, 1897", 4, 8),
    _chap(12, "Interpretation of Statutes & Foreign Contribution Regulation", 6, 12),
]
I3_CHAPTERS = [  # Taxation (Direct + Indirect combined) — 16
    _chap(1, "Basic Concepts & Residential Status", 4, 4),
    _chap(2, "Income from Salaries", 8, 10),
    _chap(3, "Income from House Property", 5, 5),
    _chap(4, "Profits & Gains of Business or Profession", 12, 12),
    _chap(5, "Capital Gains", 10, 10),
    _chap(6, "Income from Other Sources", 4, 4),
    _chap(7, "Clubbing, Set-off & Carry Forward", 6, 5),
    _chap(8, "Deductions Chapter VI-A", 8, 8),
    _chap(9, "Computation of Total Income & Tax Liability", 8, 8),
    _chap(10, "TDS, Advance Tax & Return Filing", 8, 6),
    _chap(11, "GST — Introduction, Levy & Collection", 6, 6),
    _chap(12, "Supply under GST (Time, Place, Value)", 10, 10),
    _chap(13, "Input Tax Credit (Sec 16-18)", 8, 8),
    _chap(14, "Registration under GST", 5, 4),
    _chap(15, "Tax Invoice, E-Way Bill, E-Invoicing", 5, 4),
    _chap(16, "Returns & Payment of GST", 5, 4),
]
I4_CHAPTERS = [  # Cost & Management Accounting — 15
    _chap(1, "Introduction to Cost & Management Accounting", 3, 3),
    _chap(2, "Material Cost", 6, 6),
    _chap(3, "Employee Cost & Direct Expenses", 6, 6),
    _chap(4, "Overheads — Absorption Costing", 8, 8),
    _chap(5, "Activity Based Costing", 5, 5),
    _chap(6, "Cost Sheet & Reconciliation", 6, 6),
    _chap(7, "Unit & Batch Costing", 5, 5),
    _chap(8, "Job Costing", 5, 5),
    _chap(9, "Process & Operation Costing", 10, 10),
    _chap(10, "Joint Products & By-Products", 6, 5),
    _chap(11, "Service Costing", 5, 5),
    _chap(12, "Standard Costing & Variance Analysis", 10, 12),
    _chap(13, "Marginal Costing & CVP Analysis", 8, 10),
    _chap(14, "Budgets & Budgetary Control", 8, 8),
    _chap(15, "Cost Accounting Systems", 4, 6),
]
I5_CHAPTERS = [  # Auditing & Ethics — 11
    _chap(1, "Nature, Objective & Scope of Audit", 5, 6),
    _chap(2, "Audit Strategy, Planning & Programme", 6, 8),
    _chap(3, "Audit Documentation & Evidence", 8, 12),
    _chap(4, "Risk Assessment & Internal Control", 8, 12),
    _chap(5, "Fraud & Responsibilities of the Auditor", 5, 6),
    _chap(6, "Audit in an Automated Environment", 5, 6),
    _chap(7, "Audit Sampling & Analytical Procedures", 6, 8),
    _chap(8, "Audit of Items of Financial Statements", 10, 14),
    _chap(9, "Audit of Companies (Appointment, Rights, Duties)", 8, 12),
    _chap(10, "Audit Report (CARO 2020, SA 700 series)", 8, 10),
    _chap(11, "Ethics & Terms of Audit Engagement", 5, 6),
]
I6_CHAPTERS = [  # FM + SM — 14
    _chap(1, "Scope & Objectives of Financial Management", 4, 4),
    _chap(2, "Types of Financing", 5, 5),
    _chap(3, "Financial Analysis & Planning — Ratio Analysis", 8, 10),
    _chap(4, "Cost of Capital", 7, 8),
    _chap(5, "Financing Decisions — Capital Structure", 6, 8),
    _chap(6, "Financing Decisions — Leverages", 5, 6),
    _chap(7, "Investment Decisions — Capital Budgeting", 10, 12),
    _chap(8, "Dividend Decisions", 5, 6),
    _chap(9, "Management of Working Capital", 10, 12),
    _chap(10, "Introduction to Strategic Management", 5, 5),
    _chap(11, "Strategic Analysis — External Environment", 6, 6),
    _chap(12, "Strategic Analysis — Internal Environment", 6, 6),
    _chap(13, "Strategic Choices", 6, 6),
    _chap(14, "Strategy Implementation & Evaluation", 6, 6),
]

# ----------------------- FINAL -----------------------
P1_CHAPTERS = [  # Financial Reporting — 18
    _chap(1, "Framework for Preparation & Presentation of FS", 4, 4),
    _chap(2, "Application of Indian Accounting Standards (Ind AS)", 5, 5),
    _chap(3, "Ind AS 1 — Presentation of Financial Statements", 5, 5),
    _chap(4, "Ind AS 34 — Interim Financial Reporting", 4, 4),
    _chap(5, "Ind AS on Assets (16, 38, 40, 105, 41)", 10, 8),
    _chap(6, "Ind AS on Liabilities (37, 19)", 8, 6),
    _chap(7, "Ind AS 12 — Income Taxes", 8, 6),
    _chap(8, "Ind AS 115 — Revenue from Contracts", 10, 8),
    _chap(9, "Ind AS 116 — Leases", 8, 7),
    _chap(10, "Ind AS 109/32/107 — Financial Instruments", 15, 10),
    _chap(11, "Ind AS 21 — Foreign Currency & Ind AS 29 Hyperinflation", 6, 4),
    _chap(12, "Business Combinations (Ind AS 103) — Amalgamations", 12, 8),
    _chap(13, "Consolidated Financial Statements (Ind AS 110/111/112)", 15, 10),
    _chap(14, "Investments in Associates & JVs (Ind AS 28)", 8, 5),
    _chap(15, "Share-Based Payments (Ind AS 102)", 6, 4),
    _chap(16, "Analysis of Financial Statements", 5, 3),
    _chap(17, "Integrated Reporting & Corporate Social Responsibility Reporting", 5, 2),
    _chap(18, "Accounting for Carbon Credits, Government Grants (Ind AS 20)", 6, 1),
]
P2_CHAPTERS = [  # Advanced Financial Management — 15
    _chap(1, "Financial Policy & Corporate Strategy", 4, 4),
    _chap(2, "Risk Management", 6, 6),
    _chap(3, "Advanced Capital Budgeting", 10, 10),
    _chap(4, "Security Analysis", 6, 6),
    _chap(5, "Security Valuation (DCF, Equity, Bonds)", 10, 10),
    _chap(6, "Portfolio Management (CAPM, APT, Sharpe)", 10, 10),
    _chap(7, "Securitization", 4, 3),
    _chap(8, "Mutual Funds", 5, 5),
    _chap(9, "Derivatives Analysis & Valuation", 12, 12),
    _chap(10, "Foreign Exchange Exposure & Risk Management", 8, 8),
    _chap(11, "International Financial Management", 6, 6),
    _chap(12, "Interest Rate Risk Management", 6, 6),
    _chap(13, "Corporate Valuation (M&A, LBO)", 10, 10),
    _chap(14, "Startup Finance", 4, 2),
    _chap(15, "International Financial Centre & Fintech", 4, 2),
]
P3_CHAPTERS = [  # Advanced Auditing & Ethics — 14
    _chap(1, "Quality Control & Engagement Standards Overview", 5, 5),
    _chap(2, "Audit Planning, Strategy & Execution", 6, 8),
    _chap(3, "Risk Assessment & Internal Control (SA 315/330)", 8, 10),
    _chap(4, "Special Aspects of Auditing in an Automated Environment", 6, 6),
    _chap(5, "Audit of Consolidated Financial Statements", 8, 8),
    _chap(6, "Audit of Banks", 8, 8),
    _chap(7, "Audit of Insurance Companies", 6, 6),
    _chap(8, "Audit of NBFCs", 6, 6),
    _chap(9, "Audit of Public Sector Undertakings", 4, 4),
    _chap(10, "Internal Audit, Management & Operational Audit", 5, 6),
    _chap(11, "Due Diligence, Investigation & Forensic Accounting", 6, 7),
    _chap(12, "Peer Review & Quality Review", 5, 4),
    _chap(13, "Professional Ethics — Code of Ethics of ICAI", 8, 12),
    _chap(14, "SA-Standard Auditing Reports (SA 700-720)", 8, 10),
]
P4_CHAPTERS = [  # Direct Tax Laws & International Tax — 20
    _chap(1, "Basic Concepts, Residence & Scope of Total Income", 4, 3),
    _chap(2, "Incomes Not Included in Total Income", 3, 2),
    _chap(3, "Salaries (Advanced Aspects)", 6, 5),
    _chap(4, "Income from House Property (Advanced)", 4, 3),
    _chap(5, "Profits & Gains of Business — Adv. Provisions", 12, 10),
    _chap(6, "Capital Gains (Slump Sale, Depreciable Assets, ESOPs)", 10, 10),
    _chap(7, "Income from Other Sources (Advanced)", 4, 3),
    _chap(8, "Clubbing, Set-off, Carry Forward", 5, 4),
    _chap(9, "Deductions from Gross Total Income", 6, 5),
    _chap(10, "Assessment of Companies (MAT, AMT)", 8, 8),
    _chap(11, "Assessment of Firms, LLPs, AOP/BOI", 5, 4),
    _chap(12, "Charitable & Religious Trusts", 6, 5),
    _chap(13, "Tax Planning, Tax Avoidance & GAAR", 6, 5),
    _chap(14, "TDS, TCS, Advance Tax, Interest & Refunds", 8, 8),
    _chap(15, "Assessment Procedure", 6, 5),
    _chap(16, "Appeals, Revisions, Search & Seizure", 8, 7),
    _chap(17, "Penalties, Prosecution & Settlement", 5, 3),
    _chap(18, "Transfer Pricing & Specified Domestic Transactions", 12, 8),
    _chap(19, "Non-Resident Taxation & DTAA", 10, 8),
    _chap(20, "Equalisation Levy, BEPS & Model Tax Conventions", 6, 4),
]
P5_CHAPTERS = [  # Indirect Tax Laws (GST + Customs + FTP) — 16
    _chap(1, "GST — Introduction, Levy & Collection (Sec 9)", 5, 6),
    _chap(2, "Supply, Composite & Mixed Supply, Schedules I-III", 8, 8),
    _chap(3, "Time & Value of Supply", 8, 8),
    _chap(4, "Place of Supply (Intra & Inter-state)", 6, 6),
    _chap(5, "Input Tax Credit (Sec 16-18)", 10, 12),
    _chap(6, "Registration under GST (Sec 22-30)", 5, 4),
    _chap(7, "Tax Invoice, Credit/Debit Notes, E-Invoicing", 5, 5),
    _chap(8, "Returns, Payment & Refunds", 8, 8),
    _chap(9, "Assessment, Audit & Anti-Profiteering", 6, 6),
    _chap(10, "Demands, Recovery, Offences & Penalties", 8, 6),
    _chap(11, "Advance Ruling & Appeals under GST", 6, 5),
    _chap(12, "Customs Act — Levy, Types of Duties & Valuation", 8, 8),
    _chap(13, "Customs — Importation, Exportation & Warehousing", 6, 6),
    _chap(14, "Baggage, Postal Articles, Stores & Drawback", 5, 4),
    _chap(15, "Foreign Trade Policy — Basic Concepts & Schemes", 6, 6),
    _chap(16, "GST-Customs Interaction, Special Economic Zones", 4, 2),
]
P6_CHAPTERS = [  # Integrated Business Solutions — 8 modules
    _chap(1, "Case Study Method — Approach & Framework", 4, 10),
    _chap(2, "Financial Reporting Case Studies (Ind AS)", 8, 15),
    _chap(3, "Auditing & Assurance Case Studies", 8, 15),
    _chap(4, "Direct & Indirect Tax Case Studies", 10, 15),
    _chap(5, "Advanced Financial Management Case Studies", 8, 12),
    _chap(6, "Strategic Management & Cost Case Studies", 8, 12),
    _chap(7, "Ethics, Corporate Governance & Sustainability", 6, 12),
    _chap(8, "Multi-Disciplinary Integration & Recommendations", 8, 9),
]


SYLLABUS_V2 = [
    {"level": "Foundation", "paper_code": "F1", "paper_name": "Principles and Practice of Accounting", "chapters": F1_CHAPTERS},
    {"level": "Foundation", "paper_code": "F2", "paper_name": "Business Laws & Business Correspondence and Reporting", "chapters": F2_CHAPTERS},
    {"level": "Foundation", "paper_code": "F3", "paper_name": "Business Mathematics, Logical Reasoning & Statistics", "chapters": F3_CHAPTERS},
    {"level": "Foundation", "paper_code": "F4", "paper_name": "Business Economics & Business and Commercial Knowledge", "chapters": F4_CHAPTERS},
    {"level": "Intermediate", "paper_code": "I1", "paper_name": "Advanced Accounting", "chapters": I1_CHAPTERS},
    {"level": "Intermediate", "paper_code": "I2", "paper_name": "Corporate and Other Laws", "chapters": I2_CHAPTERS},
    {"level": "Intermediate", "paper_code": "I3", "paper_name": "Taxation (Direct & Indirect)", "chapters": I3_CHAPTERS},
    {"level": "Intermediate", "paper_code": "I4", "paper_name": "Cost and Management Accounting", "chapters": I4_CHAPTERS},
    {"level": "Intermediate", "paper_code": "I5", "paper_name": "Auditing and Ethics", "chapters": I5_CHAPTERS},
    {"level": "Intermediate", "paper_code": "I6", "paper_name": "Financial and Strategic Management", "chapters": I6_CHAPTERS},
    {"level": "Final", "paper_code": "P1", "paper_name": "Financial Reporting", "chapters": P1_CHAPTERS},
    {"level": "Final", "paper_code": "P2", "paper_name": "Advanced Financial Management", "chapters": P2_CHAPTERS},
    {"level": "Final", "paper_code": "P3", "paper_name": "Advanced Auditing, Assurance and Professional Ethics", "chapters": P3_CHAPTERS},
    {"level": "Final", "paper_code": "P4", "paper_name": "Direct Tax Laws and International Taxation", "chapters": P4_CHAPTERS},
    {"level": "Final", "paper_code": "P5", "paper_name": "Indirect Tax Laws", "chapters": P5_CHAPTERS},
    {"level": "Final", "paper_code": "P6", "paper_name": "Integrated Business Solutions (Multi-disciplinary Case Study)", "chapters": P6_CHAPTERS},
]
