import React from "react";
import { Link } from "react-router-dom";
import GridBackground from "@/components/GridBackground";
import { Helmet } from "react-helmet-async";

function Section({ n, title, children }) {
  return (
    <section className="mb-14" data-testid={`legal-section-${n}`}>
      <div
        className="font-mono uppercase tracking-[0.22em] text-[10.5px] mb-3"
        style={{ color: "#8B5CF6" }}
      >
        § {String(n).padStart(2, "0")}
      </div>
      <h2
        className="font-display leading-[1.05] mb-5"
        style={{ fontSize: "clamp(28px, 4vw, 42px)", letterSpacing: "-0.02em" }}
      >
        {title}
      </h2>
      <div className="text-white/70 text-[15px] leading-[1.75] space-y-4 max-w-[68ch]">
        {children}
      </div>
    </section>
  );
}

export default function Terms() {
  return (
    <main
      className="min-h-screen relative overflow-hidden"
      style={{ background: "#0A0A0C", color: "#F2F2F2" }}
      data-testid="terms-page"
    >
      <Helmet>
        <title>Terms of Service · The CA Grid</title>
        <meta
          name="description"
          content="Terms of Service governing use of The CA Grid — a productivity platform for Indian Chartered Accountancy aspirants."
        />
        <meta name="robots" content="index,follow" />
      </Helmet>
      <GridBackground />
      <div className="relative z-10 max-w-3xl mx-auto px-6 py-24">
        <Link
          to="/"
          data-testid="terms-back-link"
          className="font-mono uppercase tracking-[0.22em] text-[10.5px] text-white/50 hover:text-white transition"
        >
          ← The CA Grid
        </Link>
        <header className="mt-10 mb-16 pb-10 border-b border-white/8">
          <div
            className="font-mono uppercase tracking-[0.22em] text-[10.5px] mb-4"
            style={{ color: "#B4FF39" }}
          >
            LEGAL · Terms of Service
          </div>
          <h1
            className="font-display leading-[0.98] mb-6"
            style={{ fontSize: "clamp(56px, 9vw, 104px)", letterSpacing: "-0.03em" }}
          >
            <em>Terms of</em>
            <br />
            Service.
          </h1>
          <div className="font-mono text-[11px] text-white/45 tracking-[0.14em]">
            Operated as an independent product · Built in India · 2026
          </div>
          <div className="font-mono text-[11px] text-white/45 tracking-[0.14em] mt-1">
            Effective: 09 Jul 2026 · Version 1.0
          </div>
        </header>

        <Section n={1} title="Acceptance">
          <p>
            By creating an account or using The CA Grid (&ldquo;the Service&rdquo;), you agree to
            these Terms. If you do not agree, do not use the Service. You must be at
            least 16 years old (or the age of digital consent in your jurisdiction) to
            use the Service.
          </p>
        </Section>

        <Section n={2} title="What The CA Grid is">
          <p>
            The CA Grid is a private study companion for Indian Chartered Accountancy
            aspirants. It provides focus tools, streak &amp; XP mechanics, analytics,
            and an AI mentor that answers subject questions. It is
            <em className="mx-1">not</em> a substitute for professional advice from a
            qualified Chartered Accountant, and content generated by the AI mentor
            should be verified against ICAI-published material before relying on it.
          </p>
        </Section>

        <Section n={3} title="Your account">
          <p>
            You are responsible for your credentials and any activity under your
            account. Choose a strong, non-obvious password. Notify us immediately if you
            believe your account has been accessed without authorisation.
          </p>
        </Section>

        <Section n={4} title="Acceptable use">
          <p>Don&apos;t do any of the following:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Attempt to break, reverse-engineer, or overload the Service.</li>
            <li>Use the AI mentor to generate content that is illegal, harmful, or defamatory.</li>
            <li>Automate scraping of the Service without written permission.</li>
            <li>Impersonate another person or misrepresent your affiliation.</li>
          </ul>
        </Section>

        <Section n={5} title="AI-generated content">
          <p>
            The AI mentor is powered by third-party large language models
            (see Privacy Policy). Outputs may contain errors, and citations are
            best-effort. You retain ownership of your prompts; you receive a
            non-exclusive licence to use AI responses for personal study.
          </p>
        </Section>

        <Section n={6} title="Availability">
          <p>
            We aim for high availability but do not guarantee uninterrupted service.
            The Service may be paused, upgraded, or discontinued with reasonable
            notice.
          </p>
        </Section>

        <Section n={7} title="Termination">
          <p>
            You may delete your account at any time from the Profile page. We may
            suspend or terminate accounts that violate these Terms, or if required by
            law. On deletion, your data is removed within 30 days from primary storage.
          </p>
        </Section>

        <Section n={8} title="Liability">
          <p>
            The Service is provided &ldquo;as is&rdquo; without warranties of any kind,
            express or implied. To the maximum extent permitted by law, The CA Grid
            shall not be liable for indirect, incidental, or consequential damages
            arising from your use of the Service. Nothing in these Terms limits
            liability that cannot be limited under applicable law.
          </p>
        </Section>

        <Section n={9} title="Changes">
          <p>
            We may update these Terms. Material changes will be announced in-product
            with reasonable notice. Continued use after changes take effect constitutes
            acceptance of the revised Terms.
          </p>
        </Section>

        <Section n={10} title="Contact">
          <p>
            Reach us at
            <a
              href="mailto:hello@cagrid.in"
              className="mx-1 underline decoration-white/20 hover:decoration-white/60"
              style={{ color: "#B4FF39" }}
            >
              hello@cagrid.in
            </a>
            for questions or notices related to these Terms.
          </p>
        </Section>

        <div className="border-t border-white/8 pt-10 mt-16 flex items-center justify-between text-xs font-mono text-white/40">
          <span>© 2026 The CA Grid</span>
          <div className="flex gap-6">
            <Link to="/privacy" className="hover:text-white transition">Privacy</Link>
            <Link to="/" className="hover:text-white transition">Home</Link>
          </div>
        </div>
      </div>
    </main>
  );
}
